// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAIRequestLog = `-- name: CreateAIRequestLog :one
INSERT INTO ai_request_logs (user_id, feature, provider, model, status)
VALUES (
    $1::bigint,
    $2,
    'stub',
    NULL,
    'queued'
)
RETURNING id, created_at
`

type CreateAIRequestLogParams struct {
	UserID  int64
	Feature pgtype.Text
}

type CreateAIRequestLogRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAIRequestLog(ctx context.Context, arg CreateAIRequestLogParams) (CreateAIRequestLogRow, error) {
	row := q.db.QueryRow(ctx, createAIRequestLog, arg.UserID, arg.Feature)
	var i CreateAIRequestLogRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const logCardGenerationRequest = `-- name: LogCardGenerationRequest :exec
INSERT INTO ai_request_logs (user_id, feature, provider, model, prompt_version, status)
VALUES (
    NULL,
    'card_generation',
    $1,
    $2,
    $3,
    $4
)
`

type LogCardGenerationRequestParams struct {
	Provider      pgtype.Text
	Model         pgtype.Text
	PromptVersion pgtype.Text
	Status        pgtype.Text
}

// Records the outcome of one CardProvisioner generation attempt (success,
// failed, or the model's own unknown_problem/quota refusal). user_id is NULL:
// the resulting cards are global, not tied to whichever user's solve event
// happened to trigger generation.
func (q *Queries) LogCardGenerationRequest(ctx context.Context, arg LogCardGenerationRequestParams) error {
	_, err := q.db.Exec(ctx, logCardGenerationRequest,
		arg.Provider,
		arg.Model,
		arg.PromptVersion,
		arg.Status,
	)
	return err
}
