// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAIRequestLog = `-- name: CreateAIRequestLog :one
INSERT INTO ai_request_logs (user_id, feature, provider, model, status)
VALUES (
    $1::bigint,
    $2,
    'openai',
    'gpt-4o-mini',
    'queued'
)
RETURNING id, created_at
`

type CreateAIRequestLogParams struct {
	UserID  int64
	Feature pgtype.Text
}

type CreateAIRequestLogRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAIRequestLog(ctx context.Context, arg CreateAIRequestLogParams) (CreateAIRequestLogRow, error) {
	row := q.db.QueryRow(ctx, createAIRequestLog, arg.UserID, arg.Feature)
	var i CreateAIRequestLogRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
