// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assistant.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishAssistantHintRequest = `-- name: FinishAssistantHintRequest :exec
UPDATE ai_request_logs
SET status = $1::text
WHERE id = $2::bigint
  AND feature = 'assistant_hint'
`

type FinishAssistantHintRequestParams struct {
	Status string
	ID     int64
}

func (q *Queries) FinishAssistantHintRequest(ctx context.Context, arg FinishAssistantHintRequestParams) error {
	_, err := q.db.Exec(ctx, finishAssistantHintRequest, arg.Status, arg.ID)
	return err
}

const getAssistantProblemContext = `-- name: GetAssistantProblemContext :one

SELECT
    p.id,
    p.title,
    p.url,
    COALESCE(p.difficulty, 'unknown')::text AS difficulty,
    pl.code AS platform,
    p.external_slug AS slug
FROM problems p
JOIN platforms pl ON pl.id = p.platform_id
WHERE pl.code = $1::text
  AND p.external_slug = $2::text
`

type GetAssistantProblemContextParams struct {
	Platform string
	Slug     string
}

type GetAssistantProblemContextRow struct {
	ID         int64
	Title      string
	Url        string
	Difficulty string
	Platform   string
	Slug       string
}

// Assistant queries: problem context for extension-driven AI hints.
func (q *Queries) GetAssistantProblemContext(ctx context.Context, arg GetAssistantProblemContextParams) (GetAssistantProblemContextRow, error) {
	row := q.db.QueryRow(ctx, getAssistantProblemContext, arg.Platform, arg.Slug)
	var i GetAssistantProblemContextRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Difficulty,
		&i.Platform,
		&i.Slug,
	)
	return i, err
}

const listAssistantProblemSubpatterns = `-- name: ListAssistantProblemSubpatterns :many
SELECT
    sp.code,
    sp.name,
    COALESCE(ps.tier, '')::text AS tier,
    COALESCE(sp.description, '')::text AS description,
    COALESCE(string_agg(DISTINCT f.name, ', ' ORDER BY f.name), '')::text AS families
FROM problem_subpatterns ps
JOIN patterns sp ON sp.id = ps.subpattern_id AND sp.kind = 'subpattern'
LEFT JOIN pattern_family_subpatterns pfs ON pfs.subpattern_id = sp.id
LEFT JOIN patterns f ON f.id = pfs.family_id AND f.kind = 'family'
WHERE ps.problem_id = $1::bigint
GROUP BY sp.code, sp.name, ps.tier, sp.description, ps.position
ORDER BY
    CASE ps.tier
        WHEN 'foundational' THEN 0
        WHEN 'core' THEN 1
        WHEN 'advanced' THEN 2
        ELSE 3
    END,
    ps.position NULLS LAST,
    sp.name
`

type ListAssistantProblemSubpatternsRow struct {
	Code        string
	Name        string
	Tier        string
	Description string
	Families    string
}

func (q *Queries) ListAssistantProblemSubpatterns(ctx context.Context, problemID int64) ([]ListAssistantProblemSubpatternsRow, error) {
	rows, err := q.db.Query(ctx, listAssistantProblemSubpatterns, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssistantProblemSubpatternsRow
	for rows.Next() {
		var i ListAssistantProblemSubpatternsRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Tier,
			&i.Description,
			&i.Families,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveAssistantHintRequest = `-- name: ReserveAssistantHintRequest :one
INSERT INTO ai_request_logs (user_id, feature, provider, model, prompt_version, status, problem_id)
VALUES (
    $1::bigint,
    'assistant_hint',
    $2::text,
    $3::text,
    $4::text,
    'queued',
    $5
)
RETURNING id
`

type ReserveAssistantHintRequestParams struct {
	UserID        int64
	Provider      string
	Model         string
	PromptVersion string
	ProblemID     pgtype.Int8
}

func (q *Queries) ReserveAssistantHintRequest(ctx context.Context, arg ReserveAssistantHintRequestParams) (int64, error) {
	row := q.db.QueryRow(ctx, reserveAssistantHintRequest,
		arg.UserID,
		arg.Provider,
		arg.Model,
		arg.PromptVersion,
		arg.ProblemID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
