// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assistant.sql

package db

import (
	"context"
)

const getAssistantProblemContext = `-- name: GetAssistantProblemContext :one

SELECT
    p.id,
    p.title,
    p.url,
    COALESCE(p.difficulty, 'unknown')::text AS difficulty,
    pl.code AS platform,
    p.external_slug AS slug
FROM problems p
JOIN platforms pl ON pl.id = p.platform_id
WHERE pl.code = $1::text
  AND p.external_slug = $2::text
`

type GetAssistantProblemContextParams struct {
	Platform string
	Slug     string
}

type GetAssistantProblemContextRow struct {
	ID         int64
	Title      string
	Url        string
	Difficulty string
	Platform   string
	Slug       string
}

// Assistant queries: problem context for extension-driven AI hints.
func (q *Queries) GetAssistantProblemContext(ctx context.Context, arg GetAssistantProblemContextParams) (GetAssistantProblemContextRow, error) {
	row := q.db.QueryRow(ctx, getAssistantProblemContext, arg.Platform, arg.Slug)
	var i GetAssistantProblemContextRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Difficulty,
		&i.Platform,
		&i.Slug,
	)
	return i, err
}

const listAssistantProblemSubpatterns = `-- name: ListAssistantProblemSubpatterns :many
SELECT
    sp.code,
    sp.name,
    COALESCE(ps.tier, '')::text AS tier,
    COALESCE(string_agg(DISTINCT f.name, ', ' ORDER BY f.name), '')::text AS families
FROM problem_subpatterns ps
JOIN patterns sp ON sp.id = ps.subpattern_id AND sp.kind = 'subpattern'
LEFT JOIN pattern_family_subpatterns pfs ON pfs.subpattern_id = sp.id
LEFT JOIN patterns f ON f.id = pfs.family_id AND f.kind = 'family'
WHERE ps.problem_id = $1::bigint
GROUP BY sp.code, sp.name, ps.tier, ps.position
ORDER BY
    CASE ps.tier
        WHEN 'foundational' THEN 0
        WHEN 'core' THEN 1
        WHEN 'advanced' THEN 2
        ELSE 3
    END,
    ps.position NULLS LAST,
    sp.name
`

type ListAssistantProblemSubpatternsRow struct {
	Code     string
	Name     string
	Tier     string
	Families string
}

func (q *Queries) ListAssistantProblemSubpatterns(ctx context.Context, problemID int64) ([]ListAssistantProblemSubpatternsRow, error) {
	rows, err := q.db.Query(ctx, listAssistantProblemSubpatterns, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssistantProblemSubpatternsRow
	for rows.Next() {
		var i ListAssistantProblemSubpatternsRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Tier,
			&i.Families,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logAssistantHintRequest = `-- name: LogAssistantHintRequest :exec
INSERT INTO ai_request_logs (user_id, feature, provider, model, status)
VALUES (
    $1::bigint,
    'assistant_hint',
    'gemini',
    $2::text,
    $3::text
)
`

type LogAssistantHintRequestParams struct {
	UserID int64
	Model  string
	Status string
}

func (q *Queries) LogAssistantHintRequest(ctx context.Context, arg LogAssistantHintRequestParams) error {
	_, err := q.db.Exec(ctx, logAssistantHintRequest, arg.UserID, arg.Model, arg.Status)
	return err
}
