// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: atlas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTaxonomyNodesByKind = `-- name: CountTaxonomyNodesByKind :many
SELECT kind, COUNT(*)::integer AS node_count
FROM patterns
WHERE taxonomy_version = $1
GROUP BY kind
ORDER BY kind
`

type CountTaxonomyNodesByKindRow struct {
	Kind      string
	NodeCount int32
}

func (q *Queries) CountTaxonomyNodesByKind(ctx context.Context, taxonomyVersion pgtype.Text) ([]CountTaxonomyNodesByKindRow, error) {
	rows, err := q.db.Query(ctx, countTaxonomyNodesByKind, taxonomyVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTaxonomyNodesByKindRow
	for rows.Next() {
		var i CountTaxonomyNodesByKindRow
		if err := rows.Scan(&i.Kind, &i.NodeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAtlasNodeByCode = `-- name: GetAtlasNodeByCode :one
SELECT
    id,
    code,
    name,
    kind,
    COALESCE(description, '')::text AS description,
    taxonomy_version,
    techniques,
    recognition_symptoms,
    checklist
FROM patterns
WHERE code = $1
`

type GetAtlasNodeByCodeRow struct {
	ID                  int64
	Code                string
	Name                string
	Kind                string
	Description         string
	TaxonomyVersion     pgtype.Text
	Techniques          []string
	RecognitionSymptoms []string
	Checklist           []string
}

func (q *Queries) GetAtlasNodeByCode(ctx context.Context, code string) (GetAtlasNodeByCodeRow, error) {
	row := q.db.QueryRow(ctx, getAtlasNodeByCode, code)
	var i GetAtlasNodeByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.TaxonomyVersion,
		&i.Techniques,
		&i.RecognitionSymptoms,
		&i.Checklist,
	)
	return i, err
}

const getPatternLearningMaterial = `-- name: GetPatternLearningMaterial :one
SELECT
    pattern_id,
    what_it_is,
    mental_model,
    recognition_cues,
    anti_cues,
    core_invariant,
    canonical_skeleton,
    common_mistakes,
    dont_confuse_with,
    mini_example
FROM pattern_learning_materials
WHERE pattern_id = $1
`

type GetPatternLearningMaterialRow struct {
	PatternID         int64
	WhatItIs          string
	MentalModel       string
	RecognitionCues   []string
	AntiCues          []string
	CoreInvariant     string
	CanonicalSkeleton string
	CommonMistakes    []string
	DontConfuseWith   []byte
	MiniExample       string
}

func (q *Queries) GetPatternLearningMaterial(ctx context.Context, patternID int64) (GetPatternLearningMaterialRow, error) {
	row := q.db.QueryRow(ctx, getPatternLearningMaterial, patternID)
	var i GetPatternLearningMaterialRow
	err := row.Scan(
		&i.PatternID,
		&i.WhatItIs,
		&i.MentalModel,
		&i.RecognitionCues,
		&i.AntiCues,
		&i.CoreInvariant,
		&i.CanonicalSkeleton,
		&i.CommonMistakes,
		&i.DontConfuseWith,
		&i.MiniExample,
	)
	return i, err
}

const listAtlasCompanies = `-- name: ListAtlasCompanies :many
SELECT
    co.code,
    co.name,
    COUNT(sc.subpattern_id)::integer AS subpattern_count,
    BOOL_AND(sc.source_type = 'demo')::boolean AS demo_only,
    MAX(sc.last_seen_at)::date AS last_seen_at
FROM companies co
JOIN subpattern_companies sc ON sc.company_id = co.id
GROUP BY co.id, co.code, co.name
ORDER BY co.name
`

type ListAtlasCompaniesRow struct {
	Code            string
	Name            string
	SubpatternCount int32
	DemoOnly        bool
	LastSeenAt      pgtype.Date
}

func (q *Queries) ListAtlasCompanies(ctx context.Context) ([]ListAtlasCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listAtlasCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAtlasCompaniesRow
	for rows.Next() {
		var i ListAtlasCompaniesRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.SubpatternCount,
			&i.DemoOnly,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyRelevantProblems = `-- name: ListCompanyRelevantProblems :many
SELECT
    p.code AS subpattern_code,
    p.name AS subpattern_name,
    COALESCE(ps.tier, '')::text AS tier,
    pr.id,
    pr.title,
    pr.url,
    COALESCE(pr.difficulty, '')::text AS difficulty,
    cp.evidence_count,
    cp.last_seen_at,
    cp.source_type,
    COALESCE(upp.status, 'not_started')::text AS status,
    rs.next_review_at
FROM company_problems cp
JOIN companies co ON co.id = cp.company_id
JOIN problems pr ON pr.id = cp.problem_id
JOIN problem_subpatterns ps ON ps.problem_id = pr.id
JOIN patterns p ON p.id = ps.subpattern_id
LEFT JOIN user_problem_progress upp
    ON upp.problem_id = pr.id AND upp.user_id = $1::bigint
LEFT JOIN review_schedules rs
    ON rs.problem_id = pr.id AND rs.user_id = $1::bigint
WHERE co.code = $2::text
ORDER BY p.code, ps.tier, pr.title
`

type ListCompanyRelevantProblemsParams struct {
	UserID      int64
	CompanyCode string
}

type ListCompanyRelevantProblemsRow struct {
	SubpatternCode string
	SubpatternName string
	Tier           string
	ID             int64
	Title          string
	Url            string
	Difficulty     string
	EvidenceCount  int32
	LastSeenAt     pgtype.Date
	SourceType     string
	Status         string
	NextReviewAt   pgtype.Timestamptz
}

// Company-scoped practice: every problem with evidence for a company,
// joined to the subpatterns it practices. Drives the readiness overlay so
// relevant tasks can surface next to relevant subpatterns. A problem that
// practices several subpatterns repeats once per link.
func (q *Queries) ListCompanyRelevantProblems(ctx context.Context, arg ListCompanyRelevantProblemsParams) ([]ListCompanyRelevantProblemsRow, error) {
	rows, err := q.db.Query(ctx, listCompanyRelevantProblems, arg.UserID, arg.CompanyCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompanyRelevantProblemsRow
	for rows.Next() {
		var i ListCompanyRelevantProblemsRow
		if err := rows.Scan(
			&i.SubpatternCode,
			&i.SubpatternName,
			&i.Tier,
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Difficulty,
			&i.EvidenceCount,
			&i.LastSeenAt,
			&i.SourceType,
			&i.Status,
			&i.NextReviewAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanySubpatternRelevance = `-- name: ListCompanySubpatternRelevance :many
SELECT
    p.code,
    sc.relevance,
    sc.confidence,
    sc.evidence_count,
    sc.last_seen_at,
    sc.source_type
FROM subpattern_companies sc
JOIN companies co ON co.id = sc.company_id
JOIN patterns p ON p.id = sc.subpattern_id
WHERE co.code = $1
`

type ListCompanySubpatternRelevanceRow struct {
	Code          string
	Relevance     string
	Confidence    string
	EvidenceCount int32
	LastSeenAt    pgtype.Date
	SourceType    string
}

func (q *Queries) ListCompanySubpatternRelevance(ctx context.Context, code string) ([]ListCompanySubpatternRelevanceRow, error) {
	rows, err := q.db.Query(ctx, listCompanySubpatternRelevance, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompanySubpatternRelevanceRow
	for rows.Next() {
		var i ListCompanySubpatternRelevanceRow
		if err := rows.Scan(
			&i.Code,
			&i.Relevance,
			&i.Confidence,
			&i.EvidenceCount,
			&i.LastSeenAt,
			&i.SourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFamilySubpatternEdges = `-- name: ListFamilySubpatternEdges :many
SELECT
    f.code AS family_code,
    s.code AS subpattern_code,
    e.position
FROM pattern_family_subpatterns e
JOIN patterns f ON f.id = e.family_id
JOIN patterns s ON s.id = e.subpattern_id
ORDER BY f.position, e.position
`

type ListFamilySubpatternEdgesRow struct {
	FamilyCode     string
	SubpatternCode string
	Position       int32
}

func (q *Queries) ListFamilySubpatternEdges(ctx context.Context) ([]ListFamilySubpatternEdgesRow, error) {
	rows, err := q.db.Query(ctx, listFamilySubpatternEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFamilySubpatternEdgesRow
	for rows.Next() {
		var i ListFamilySubpatternEdgesRow
		if err := rows.Scan(&i.FamilyCode, &i.SubpatternCode, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatternCardSummaries = `-- name: ListPatternCardSummaries :many
SELECT
    c.id,
    c.type,
    c.question,
    rs.next_review_at,
    rs.last_rating
FROM cards c
LEFT JOIN review_schedules rs
    ON rs.card_id = c.id AND rs.user_id = $1::bigint
WHERE c.pattern_id = $2::bigint
  AND (c.user_id IS NULL OR c.user_id = $1::bigint)
ORDER BY c.created_at, c.id
`

type ListPatternCardSummariesParams struct {
	UserID    int64
	PatternID int64
}

type ListPatternCardSummariesRow struct {
	ID           int64
	Type         string
	Question     string
	NextReviewAt pgtype.Timestamptz
	LastRating   pgtype.Text
}

// Card summaries for a taxonomy node's detail view (shared + own cards).
func (q *Queries) ListPatternCardSummaries(ctx context.Context, arg ListPatternCardSummariesParams) ([]ListPatternCardSummariesRow, error) {
	rows, err := q.db.Query(ctx, listPatternCardSummaries, arg.UserID, arg.PatternID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatternCardSummariesRow
	for rows.Next() {
		var i ListPatternCardSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Question,
			&i.NextReviewAt,
			&i.LastRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubpatternCardCounts = `-- name: ListSubpatternCardCounts :many
SELECT
    p.code,
    COUNT(*)::integer AS card_count
FROM cards c
JOIN patterns p ON p.id = c.pattern_id AND p.kind = 'subpattern'
WHERE c.user_id IS NULL OR c.user_id = $1::bigint
GROUP BY p.code
`

type ListSubpatternCardCountsRow struct {
	Code      string
	CardCount int32
}

func (q *Queries) ListSubpatternCardCounts(ctx context.Context, dollar_1 int64) ([]ListSubpatternCardCountsRow, error) {
	rows, err := q.db.Query(ctx, listSubpatternCardCounts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubpatternCardCountsRow
	for rows.Next() {
		var i ListSubpatternCardCountsRow
		if err := rows.Scan(&i.Code, &i.CardCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubpatternCompanyProblems = `-- name: ListSubpatternCompanyProblems :many
SELECT
    co.code AS company_code,
    co.name AS company_name,
    pr.id,
    pr.title,
    pr.url,
    COALESCE(pr.difficulty, '')::text AS difficulty,
    cp.evidence_count,
    cp.last_seen_at,
    cp.source_type,
    COALESCE(upp.status, 'not_started')::text AS status,
    rs.next_review_at
FROM problem_subpatterns ps
JOIN company_problems cp ON cp.problem_id = ps.problem_id
JOIN companies co ON co.id = cp.company_id
JOIN problems pr ON pr.id = ps.problem_id
LEFT JOIN user_problem_progress upp
    ON upp.problem_id = pr.id AND upp.user_id = $1::bigint
LEFT JOIN review_schedules rs
    ON rs.problem_id = pr.id AND rs.user_id = $1::bigint
WHERE ps.subpattern_id = $2::bigint
ORDER BY co.name, pr.title
`

type ListSubpatternCompanyProblemsParams struct {
	UserID       int64
	SubpatternID int64
}

type ListSubpatternCompanyProblemsRow struct {
	CompanyCode   string
	CompanyName   string
	ID            int64
	Title         string
	Url           string
	Difficulty    string
	EvidenceCount int32
	LastSeenAt    pgtype.Date
	SourceType    string
	Status        string
	NextReviewAt  pgtype.Timestamptz
}

// Company-specific practice: problems of this subpattern that carry
// evidence records for a company.
func (q *Queries) ListSubpatternCompanyProblems(ctx context.Context, arg ListSubpatternCompanyProblemsParams) ([]ListSubpatternCompanyProblemsRow, error) {
	rows, err := q.db.Query(ctx, listSubpatternCompanyProblems, arg.UserID, arg.SubpatternID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubpatternCompanyProblemsRow
	for rows.Next() {
		var i ListSubpatternCompanyProblemsRow
		if err := rows.Scan(
			&i.CompanyCode,
			&i.CompanyName,
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Difficulty,
			&i.EvidenceCount,
			&i.LastSeenAt,
			&i.SourceType,
			&i.Status,
			&i.NextReviewAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubpatternDifficultyCounts = `-- name: ListSubpatternDifficultyCounts :many
SELECT
    sp.code,
    COALESCE(pr.difficulty, 'unknown')::text AS difficulty,
    COUNT(*)::integer AS problem_count
FROM patterns sp
JOIN problem_subpatterns ps ON ps.subpattern_id = sp.id
JOIN problems pr ON pr.id = ps.problem_id
WHERE sp.kind = 'subpattern'
GROUP BY sp.code, COALESCE(pr.difficulty, 'unknown')
`

type ListSubpatternDifficultyCountsRow struct {
	Code         string
	Difficulty   string
	ProblemCount int32
}

// Catalog-wide difficulty distribution of each subpattern's practice set
// (not user-specific; merged into the same stats struct for the tree view).
func (q *Queries) ListSubpatternDifficultyCounts(ctx context.Context) ([]ListSubpatternDifficultyCountsRow, error) {
	rows, err := q.db.Query(ctx, listSubpatternDifficultyCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubpatternDifficultyCountsRow
	for rows.Next() {
		var i ListSubpatternDifficultyCountsRow
		if err := rows.Scan(&i.Code, &i.Difficulty, &i.ProblemCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubpatternFamilies = `-- name: ListSubpatternFamilies :many
SELECT f.code, f.name
FROM pattern_family_subpatterns e
JOIN patterns f ON f.id = e.family_id
WHERE e.subpattern_id = $1
ORDER BY f.position
`

type ListSubpatternFamiliesRow struct {
	Code string
	Name string
}

func (q *Queries) ListSubpatternFamilies(ctx context.Context, subpatternID int64) ([]ListSubpatternFamiliesRow, error) {
	rows, err := q.db.Query(ctx, listSubpatternFamilies, subpatternID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubpatternFamiliesRow
	for rows.Next() {
		var i ListSubpatternFamiliesRow
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubpatternPracticeProblems = `-- name: ListSubpatternPracticeProblems :many
SELECT
    pr.id,
    pr.title,
    pr.url,
    COALESCE(pr.difficulty, '')::text AS difficulty,
    COALESCE(ps.tier, '')::text AS tier,
    COALESCE(upp.status, 'not_started')::text AS status,
    pl.code AS platform,
    upp.rating,
    upp.solved_at,
    rs.next_review_at
FROM problem_subpatterns ps
JOIN problems pr ON pr.id = ps.problem_id
JOIN platforms pl ON pl.id = pr.platform_id
LEFT JOIN user_problem_progress upp
    ON upp.problem_id = pr.id AND upp.user_id = $1::bigint
LEFT JOIN review_schedules rs
    ON rs.problem_id = pr.id AND rs.user_id = $1::bigint
WHERE ps.subpattern_id = $2::bigint
    AND ($3::text = '' OR pl.code = $3::text)
ORDER BY
    CASE ps.tier
        WHEN 'foundational' THEN 0
        WHEN 'core' THEN 1
        WHEN 'advanced' THEN 2
        ELSE 3
    END,
    ps.position NULLS LAST,
    pr.title
`

type ListSubpatternPracticeProblemsParams struct {
	UserID       int64
	SubpatternID int64
	PlatformCode string
}

type ListSubpatternPracticeProblemsRow struct {
	ID           int64
	Title        string
	Url          string
	Difficulty   string
	Tier         string
	Status       string
	Platform     string
	Rating       pgtype.Text
	SolvedAt     pgtype.Timestamptz
	NextReviewAt pgtype.Timestamptz
}

// General practice set of a subpattern with the user's state.
func (q *Queries) ListSubpatternPracticeProblems(ctx context.Context, arg ListSubpatternPracticeProblemsParams) ([]ListSubpatternPracticeProblemsRow, error) {
	rows, err := q.db.Query(ctx, listSubpatternPracticeProblems, arg.UserID, arg.SubpatternID, arg.PlatformCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubpatternPracticeProblemsRow
	for rows.Next() {
		var i ListSubpatternPracticeProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Difficulty,
			&i.Tier,
			&i.Status,
			&i.Platform,
			&i.Rating,
			&i.SolvedAt,
			&i.NextReviewAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubpatternPrerequisiteEdges = `-- name: ListSubpatternPrerequisiteEdges :many
SELECT
    s.code AS subpattern_code,
    t.code AS tool_code
FROM subpattern_prerequisites sp
JOIN patterns s ON s.id = sp.subpattern_id
JOIN patterns t ON t.id = sp.tool_id
ORDER BY s.position, t.position
`

type ListSubpatternPrerequisiteEdgesRow struct {
	SubpatternCode string
	ToolCode       string
}

func (q *Queries) ListSubpatternPrerequisiteEdges(ctx context.Context) ([]ListSubpatternPrerequisiteEdgesRow, error) {
	rows, err := q.db.Query(ctx, listSubpatternPrerequisiteEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubpatternPrerequisiteEdgesRow
	for rows.Next() {
		var i ListSubpatternPrerequisiteEdgesRow
		if err := rows.Scan(&i.SubpatternCode, &i.ToolCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubpatternRelevantCompanies = `-- name: ListSubpatternRelevantCompanies :many
SELECT
    co.code,
    co.name,
    sc.relevance,
    sc.confidence,
    sc.evidence_count,
    sc.last_seen_at,
    sc.source_type
FROM subpattern_companies sc
JOIN companies co ON co.id = sc.company_id
WHERE sc.subpattern_id = $1
ORDER BY
    CASE sc.relevance
        WHEN 'high' THEN 0
        WHEN 'medium' THEN 1
        WHEN 'low' THEN 2
        WHEN 'insufficient_evidence' THEN 3
        ELSE 4
    END,
    co.name
`

type ListSubpatternRelevantCompaniesRow struct {
	Code          string
	Name          string
	Relevance     string
	Confidence    string
	EvidenceCount int32
	LastSeenAt    pgtype.Date
	SourceType    string
}

func (q *Queries) ListSubpatternRelevantCompanies(ctx context.Context, subpatternID int64) ([]ListSubpatternRelevantCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listSubpatternRelevantCompanies, subpatternID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubpatternRelevantCompaniesRow
	for rows.Next() {
		var i ListSubpatternRelevantCompaniesRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Relevance,
			&i.Confidence,
			&i.EvidenceCount,
			&i.LastSeenAt,
			&i.SourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubpatternTools = `-- name: ListSubpatternTools :many
SELECT t.code, t.name
FROM subpattern_prerequisites sp
JOIN patterns t ON t.id = sp.tool_id
WHERE sp.subpattern_id = $1
ORDER BY t.position
`

type ListSubpatternToolsRow struct {
	Code string
	Name string
}

func (q *Queries) ListSubpatternTools(ctx context.Context, subpatternID int64) ([]ListSubpatternToolsRow, error) {
	rows, err := q.db.Query(ctx, listSubpatternTools, subpatternID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubpatternToolsRow
	for rows.Next() {
		var i ListSubpatternToolsRow
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxonomyNodes = `-- name: ListTaxonomyNodes :many

SELECT
    id,
    code,
    name,
    kind,
    COALESCE(description, '')::text AS description,
    COALESCE(position, 0)::integer AS position
FROM patterns
WHERE taxonomy_version = $1
ORDER BY kind, position, code
`

type ListTaxonomyNodesRow struct {
	ID          int64
	Code        string
	Name        string
	Kind        string
	Description string
	Position    int32
}

// Pattern Atlas queries: Realgo Taxonomy nodes, many-to-many edges,
// per-user subpattern stats and the company relevance overlay.
// Each atlas page load is a fixed, small set of flat queries (no N+1).
func (q *Queries) ListTaxonomyNodes(ctx context.Context, taxonomyVersion pgtype.Text) ([]ListTaxonomyNodesRow, error) {
	rows, err := q.db.Query(ctx, listTaxonomyNodes, taxonomyVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaxonomyNodesRow
	for rows.Next() {
		var i ListTaxonomyNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Kind,
			&i.Description,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSubpatternAttemptStats = `-- name: ListUserSubpatternAttemptStats :many
WITH mapped AS (
    SELECT ps.subpattern_id, ra.rating, ra.created_at
    FROM review_attempts ra
    JOIN problem_subpatterns ps ON ps.problem_id = ra.problem_id
    WHERE ra.user_id = $1::bigint
    UNION ALL
    SELECT p.id, ra.rating, ra.created_at
    FROM review_attempts ra
    JOIN patterns p ON p.id = ra.pattern_id AND p.kind = 'subpattern'
    WHERE ra.user_id = $1::bigint
    UNION ALL
    SELECT p.id, ra.rating, ra.created_at
    FROM review_attempts ra
    JOIN cards c ON c.id = ra.card_id AND c.pattern_id IS NOT NULL
    JOIN patterns p ON p.id = c.pattern_id AND p.kind = 'subpattern'
    WHERE ra.user_id = $1::bigint
)
SELECT
    p.code,
    COUNT(*)::integer AS attempt_count,
    COUNT(*) FILTER (WHERE m.rating = 'hard')::integer AS hard_count,
    MAX(m.created_at)::timestamptz AS last_attempt_at
FROM mapped m
JOIN patterns p ON p.id = m.subpattern_id
GROUP BY p.code
`

type ListUserSubpatternAttemptStatsRow struct {
	Code          string
	AttemptCount  int32
	HardCount     int32
	LastAttemptAt pgtype.Timestamptz
}

// Review attempts mapped onto subpatterns through any of the three review
// targets: the subpattern's problems, the subpattern node itself, or cards
// attached to the subpattern node.
func (q *Queries) ListUserSubpatternAttemptStats(ctx context.Context, dollar_1 int64) ([]ListUserSubpatternAttemptStatsRow, error) {
	rows, err := q.db.Query(ctx, listUserSubpatternAttemptStats, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSubpatternAttemptStatsRow
	for rows.Next() {
		var i ListUserSubpatternAttemptStatsRow
		if err := rows.Scan(
			&i.Code,
			&i.AttemptCount,
			&i.HardCount,
			&i.LastAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSubpatternProblemStats = `-- name: ListUserSubpatternProblemStats :many
SELECT
    sp.code,
    COUNT(ps.problem_id)::integer AS problem_count,
    COUNT(*) FILTER (WHERE upp.status IN ('solved', 'reviewing'))::integer AS solved_count,
    COUNT(*) FILTER (WHERE upp.status = 'in_progress')::integer AS in_progress_count,
    COUNT(*) FILTER (WHERE rs.next_review_at <= NOW())::integer AS due_problem_count,
    MAX(upp.solved_at)::timestamptz AS last_solved_at
FROM patterns sp
JOIN problem_subpatterns ps ON ps.subpattern_id = sp.id
LEFT JOIN user_problem_progress upp
    ON upp.problem_id = ps.problem_id AND upp.user_id = $1::bigint
LEFT JOIN review_schedules rs
    ON rs.problem_id = ps.problem_id AND rs.user_id = $1::bigint
WHERE sp.kind = 'subpattern'
GROUP BY sp.code
`

type ListUserSubpatternProblemStatsRow struct {
	Code            string
	ProblemCount    int32
	SolvedCount     int32
	InProgressCount int32
	DueProblemCount int32
	LastSolvedAt    pgtype.Timestamptz
}

// Per-subpattern practice progress: linked problems, solved/in-progress
// counts, due problem reviews.
func (q *Queries) ListUserSubpatternProblemStats(ctx context.Context, dollar_1 int64) ([]ListUserSubpatternProblemStatsRow, error) {
	rows, err := q.db.Query(ctx, listUserSubpatternProblemStats, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSubpatternProblemStatsRow
	for rows.Next() {
		var i ListUserSubpatternProblemStatsRow
		if err := rows.Scan(
			&i.Code,
			&i.ProblemCount,
			&i.SolvedCount,
			&i.InProgressCount,
			&i.DueProblemCount,
			&i.LastSolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSubpatternReviewStats = `-- name: ListUserSubpatternReviewStats :many
WITH targets AS (
    SELECT p.id AS subpattern_id, rs.next_review_at
    FROM review_schedules rs
    JOIN patterns p ON p.id = rs.pattern_id AND p.kind = 'subpattern'
    WHERE rs.user_id = $1::bigint
    UNION ALL
    SELECT p.id, rs.next_review_at
    FROM review_schedules rs
    JOIN cards c ON c.id = rs.card_id AND c.pattern_id IS NOT NULL
    JOIN patterns p ON p.id = c.pattern_id AND p.kind = 'subpattern'
    WHERE rs.user_id = $1::bigint
)
SELECT
    p.code,
    COUNT(*) FILTER (WHERE t.next_review_at <= NOW())::integer AS due_count,
    MIN(t.next_review_at)::timestamptz AS next_review_at
FROM targets t
JOIN patterns p ON p.id = t.subpattern_id
GROUP BY p.code
`

type ListUserSubpatternReviewStatsRow struct {
	Code         string
	DueCount     int32
	NextReviewAt pgtype.Timestamptz
}

// Spaced-repetition state that targets the subpattern itself (node reviews
// and cards attached to the node).
func (q *Queries) ListUserSubpatternReviewStats(ctx context.Context, dollar_1 int64) ([]ListUserSubpatternReviewStatsRow, error) {
	rows, err := q.db.Query(ctx, listUserSubpatternReviewStats, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSubpatternReviewStatsRow
	for rows.Next() {
		var i ListUserSubpatternReviewStatsRow
		if err := rows.Scan(&i.Code, &i.DueCount, &i.NextReviewAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
