// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCardScheduleForUser = `-- name: GetCardScheduleForUser :one
SELECT rs.id
FROM review_schedules rs
WHERE rs.card_id  = $1::bigint
  AND rs.user_id  = $2::bigint
`

type GetCardScheduleForUserParams struct {
	Column1 int64
	Column2 int64
}

// Resolve review_schedule.id for a (card_id, user_id) pair.
func (q *Queries) GetCardScheduleForUser(ctx context.Context, arg GetCardScheduleForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCardScheduleForUser, arg.Column1, arg.Column2)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listDueCardSessions = `-- name: ListDueCardSessions :many
SELECT
    rs.id            AS schedule_id,
    c.id             AS card_id,
    c.type,
    c.question,
    c.answer,
    c.explanation,
    p.title          AS problem_title,
    p.url            AS problem_url,
    pat.name         AS pattern_name,
    rs.next_review_at,
    rs.last_rating,
    COALESCE(rs.review_count, 0)::int AS review_count,
    rs.state
FROM review_schedules rs
JOIN cards c           ON c.id   = rs.card_id
LEFT JOIN problems p   ON p.id   = c.problem_id
LEFT JOIN patterns pat ON pat.id = c.pattern_id
WHERE rs.user_id     = $1::bigint
  AND rs.card_id     IS NOT NULL
  AND rs.next_review_at <= NOW()
ORDER BY rs.next_review_at ASC
LIMIT $2::int
`

type ListDueCardSessionsParams struct {
	Column1 int64
	Column2 int32
}

type ListDueCardSessionsRow struct {
	ScheduleID   int64
	CardID       int64
	Type         string
	Question     string
	Answer       string
	Explanation  pgtype.Text
	ProblemTitle pgtype.Text
	ProblemUrl   pgtype.Text
	PatternName  pgtype.Text
	NextReviewAt pgtype.Timestamptz
	LastRating   pgtype.Text
	ReviewCount  int32
	State        int16
}

// Cards due for review (next_review_at <= NOW()), with full card content.
func (q *Queries) ListDueCardSessions(ctx context.Context, arg ListDueCardSessionsParams) ([]ListDueCardSessionsRow, error) {
	rows, err := q.db.Query(ctx, listDueCardSessions, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueCardSessionsRow
	for rows.Next() {
		var i ListDueCardSessionsRow
		if err := rows.Scan(
			&i.ScheduleID,
			&i.CardID,
			&i.Type,
			&i.Question,
			&i.Answer,
			&i.Explanation,
			&i.ProblemTitle,
			&i.ProblemUrl,
			&i.PatternName,
			&i.NextReviewAt,
			&i.LastRating,
			&i.ReviewCount,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCards = `-- name: ListUserCards :many
SELECT
    c.id,
    c.type,
    c.question,
    c.answer,
    c.explanation,
    c.source,
    c.created_by_ai,
    c.created_at,
    p.title          AS problem_title,
    p.url            AS problem_url,
    pat.name         AS pattern_name,
    rs.id            AS schedule_id,
    rs.next_review_at,
    rs.last_rating,
    COALESCE(rs.review_count, 0)::int AS review_count,
    rs.state
FROM cards c
LEFT JOIN problems p   ON p.id   = c.problem_id
LEFT JOIN patterns pat ON pat.id = c.pattern_id
LEFT JOIN review_schedules rs ON rs.card_id = c.id AND rs.user_id = c.user_id
WHERE c.user_id = $1::bigint
ORDER BY c.created_at DESC
LIMIT $2::int
`

type ListUserCardsParams struct {
	Column1 int64
	Column2 int32
}

type ListUserCardsRow struct {
	ID           int64
	Type         string
	Question     string
	Answer       string
	Explanation  pgtype.Text
	Source       pgtype.Text
	CreatedByAi  pgtype.Bool
	CreatedAt    pgtype.Timestamptz
	ProblemTitle pgtype.Text
	ProblemUrl   pgtype.Text
	PatternName  pgtype.Text
	ScheduleID   pgtype.Int8
	NextReviewAt pgtype.Timestamptz
	LastRating   pgtype.Text
	ReviewCount  int32
	State        pgtype.Int2
}

// All cards owned by the user, newest first, with schedule status.
func (q *Queries) ListUserCards(ctx context.Context, arg ListUserCardsParams) ([]ListUserCardsRow, error) {
	rows, err := q.db.Query(ctx, listUserCards, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserCardsRow
	for rows.Next() {
		var i ListUserCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Question,
			&i.Answer,
			&i.Explanation,
			&i.Source,
			&i.CreatedByAi,
			&i.CreatedAt,
			&i.ProblemTitle,
			&i.ProblemUrl,
			&i.PatternName,
			&i.ScheduleID,
			&i.NextReviewAt,
			&i.LastRating,
			&i.ReviewCount,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
