// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCardSessionAttempts = `-- name: CountCardSessionAttempts :one
SELECT COUNT(*)::integer
FROM review_attempts
WHERE user_id = $1
  AND card_id IS NOT NULL
  AND created_at >= $2
`

type CountCardSessionAttemptsParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountCardSessionAttempts(ctx context.Context, arg CountCardSessionAttemptsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countCardSessionAttempts, arg.UserID, arg.CreatedAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createCardReviewSchedule = `-- name: CreateCardReviewSchedule :one
INSERT INTO review_schedules (
    user_id, card_id, next_review_at, interval_days,
    ease, stability, difficulty, review_count, algorithm
)
VALUES ($1, $2, $3, 0, 2.5, 0.1, 5.0, 0, 'fsrs')
RETURNING id
`

type CreateCardReviewScheduleParams struct {
	UserID       int64
	CardID       pgtype.Int8
	NextReviewAt pgtype.Timestamptz
}

func (q *Queries) CreateCardReviewSchedule(ctx context.Context, arg CreateCardReviewScheduleParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCardReviewSchedule, arg.UserID, arg.CardID, arg.NextReviewAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAccessibleCard = `-- name: GetAccessibleCard :one
SELECT c.id
FROM cards c
WHERE c.id = $1::bigint
  AND (
    c.user_id = $2::bigint
    OR c.user_id IS NULL
    OR EXISTS (
        SELECT 1
        FROM review_schedules rs
        WHERE rs.user_id = $2::bigint AND rs.card_id = c.id
    )
  )
`

type GetAccessibleCardParams struct {
	CardID int64
	UserID int64
}

func (q *Queries) GetAccessibleCard(ctx context.Context, arg GetAccessibleCardParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAccessibleCard, arg.CardID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCardReviewSchedule = `-- name: GetCardReviewSchedule :one
SELECT id
FROM review_schedules
WHERE user_id = $1 AND card_id = $2
ORDER BY id ASC
LIMIT 1
`

type GetCardReviewScheduleParams struct {
	UserID int64
	CardID pgtype.Int8
}

func (q *Queries) GetCardReviewSchedule(ctx context.Context, arg GetCardReviewScheduleParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCardReviewSchedule, arg.UserID, arg.CardID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCardSession = `-- name: ListCardSession :many
SELECT
    c.id,
    c.type,
    c.question,
    c.answer,
    c.created_at,
    CASE
        WHEN c.problem_id IS NOT NULL THEN 'problem'
        WHEN c.pattern_id IS NOT NULL THEN 'pattern'
        ELSE 'custom'
    END::text AS source_entity_type,
    COALESCE(c.problem_id, c.pattern_id) AS source_entity_id,
    COALESCE(
        NULLIF(concat_ws(' · ', NULLIF(p.title, ''), NULLIF(COALESCE(cpt.name, rpt.name), '')), ''),
        NULLIF(cpt.name, ''),
        NULLIF(c.source, ''),
        'custom card'
    )::text AS source_label,
    COALESCE(rs.id, 0)::bigint AS schedule_id,
    rs.next_review_at,
    rs.last_rating,
    COALESCE(rs.review_count, 0)::integer AS review_count,
    COALESCE(rs.state, 0)::integer AS review_state
FROM cards c
LEFT JOIN LATERAL (
    SELECT id, next_review_at, last_rating, review_count, state
    FROM review_schedules
    WHERE user_id = $1::bigint AND card_id = c.id
    ORDER BY next_review_at ASC, id ASC
    LIMIT 1
) rs ON true
LEFT JOIN problems p ON p.id = c.problem_id
LEFT JOIN patterns cpt ON cpt.id = c.pattern_id
LEFT JOIN roadmap_items ri ON ri.problem_id = c.problem_id AND ri.roadmap_code = 'neetcode_150'
LEFT JOIN patterns rpt ON rpt.id = ri.pattern_id
WHERE (c.user_id = $1::bigint OR c.user_id IS NULL OR rs.id IS NOT NULL)
  AND (
    ($2::text = 'due' AND rs.next_review_at <= NOW())
    OR ($2::text = 'hard_normal' AND rs.last_rating IN ('hard', 'normal'))
    OR ($2::text = 'all')
  )
ORDER BY
    CASE
        WHEN rs.next_review_at <= NOW() THEN 0
        WHEN rs.id IS NULL THEN 1
        ELSE 2
    END,
    rs.next_review_at ASC NULLS LAST,
    c.created_at DESC,
    c.id DESC
LIMIT $3::integer
`

type ListCardSessionParams struct {
	UserID    int64
	Scope     string
	CardLimit int32
}

type ListCardSessionRow struct {
	ID               int64
	Type             string
	Question         string
	Answer           string
	CreatedAt        pgtype.Timestamptz
	SourceEntityType string
	SourceEntityID   pgtype.Int8
	SourceLabel      string
	ScheduleID       int64
	NextReviewAt     pgtype.Timestamptz
	LastRating       pgtype.Text
	ReviewCount      int32
	ReviewState      int32
}

func (q *Queries) ListCardSession(ctx context.Context, arg ListCardSessionParams) ([]ListCardSessionRow, error) {
	rows, err := q.db.Query(ctx, listCardSession, arg.UserID, arg.Scope, arg.CardLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardSessionRow
	for rows.Next() {
		var i ListCardSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Question,
			&i.Answer,
			&i.CreatedAt,
			&i.SourceEntityType,
			&i.SourceEntityID,
			&i.SourceLabel,
			&i.ScheduleID,
			&i.NextReviewAt,
			&i.LastRating,
			&i.ReviewCount,
			&i.ReviewState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCards = `-- name: ListUserCards :many
SELECT
    c.id,
    c.type,
    c.question,
    c.answer,
    c.created_at,
    CASE
        WHEN c.problem_id IS NOT NULL THEN 'problem'
        WHEN c.pattern_id IS NOT NULL THEN 'pattern'
        ELSE 'custom'
    END::text AS source_entity_type,
    COALESCE(c.problem_id, c.pattern_id) AS source_entity_id,
    COALESCE(
        NULLIF(concat_ws(' · ', NULLIF(p.title, ''), NULLIF(COALESCE(cpt.name, rpt.name), '')), ''),
        NULLIF(cpt.name, ''),
        NULLIF(c.source, ''),
        'custom card'
    )::text AS source_label,
    COALESCE(rs.id, 0)::bigint AS schedule_id,
    rs.next_review_at,
    rs.last_rating,
    COALESCE(rs.review_count, 0)::integer AS review_count,
    COALESCE(rs.state, 0)::integer AS review_state
FROM cards c
LEFT JOIN LATERAL (
    SELECT id, next_review_at, last_rating, review_count, state
    FROM review_schedules
    WHERE user_id = $1::bigint AND card_id = c.id
    ORDER BY next_review_at ASC, id ASC
    LIMIT 1
) rs ON true
LEFT JOIN problems p ON p.id = c.problem_id
LEFT JOIN patterns cpt ON cpt.id = c.pattern_id
LEFT JOIN roadmap_items ri ON ri.problem_id = c.problem_id AND ri.roadmap_code = 'neetcode_150'
LEFT JOIN patterns rpt ON rpt.id = ri.pattern_id
WHERE (c.user_id = $1::bigint OR c.user_id IS NULL OR rs.id IS NOT NULL)
  AND ($2::text = '' OR c.type = $2::text)
  AND (c.created_at, c.id) < ($3::timestamptz, $4::bigint)
ORDER BY c.created_at DESC, c.id DESC
LIMIT $5::integer
`

type ListUserCardsParams struct {
	UserID          int64
	CardType        string
	CursorCreatedAt pgtype.Timestamptz
	CursorID        int64
	LimitRows       int32
}

type ListUserCardsRow struct {
	ID               int64
	Type             string
	Question         string
	Answer           string
	CreatedAt        pgtype.Timestamptz
	SourceEntityType string
	SourceEntityID   pgtype.Int8
	SourceLabel      string
	ScheduleID       int64
	NextReviewAt     pgtype.Timestamptz
	LastRating       pgtype.Text
	ReviewCount      int32
	ReviewState      int32
}

func (q *Queries) ListUserCards(ctx context.Context, arg ListUserCardsParams) ([]ListUserCardsRow, error) {
	rows, err := q.db.Query(ctx, listUserCards,
		arg.UserID,
		arg.CardType,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserCardsRow
	for rows.Next() {
		var i ListUserCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Question,
			&i.Answer,
			&i.CreatedAt,
			&i.SourceEntityType,
			&i.SourceEntityID,
			&i.SourceLabel,
			&i.ScheduleID,
			&i.NextReviewAt,
			&i.LastRating,
			&i.ReviewCount,
			&i.ReviewState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
