// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCardSessionAttempts = `-- name: CountCardSessionAttempts :one
SELECT COUNT(*)::integer
FROM review_attempts
WHERE user_id = $1
  AND card_id IS NOT NULL
  AND created_at >= $2
`

type CountCardSessionAttemptsParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountCardSessionAttempts(ctx context.Context, arg CountCardSessionAttemptsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countCardSessionAttempts, arg.UserID, arg.CreatedAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countGlobalAICardsByProblem = `-- name: CountGlobalAICardsByProblem :one
SELECT COUNT(*)::bigint
FROM cards
WHERE problem_id = $1::bigint
  AND user_id IS NULL
  AND created_by_ai = TRUE
`

// Idempotency check for CardProvisioner: has this problem already been
// globally AI-provisioned, regardless of which user triggers generation.
func (q *Queries) CountGlobalAICardsByProblem(ctx context.Context, problemID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countGlobalAICardsByProblem, problemID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCard = `-- name: CreateCard :one
INSERT INTO cards (user_id, problem_id, pattern_id, type, question, answer, explanation, source, created_by_ai)
VALUES (
    $1::bigint,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, user_id, problem_id, pattern_id, type, question, answer, explanation, source, created_by_ai, created_at, ai_prompt_version
`

type CreateCardParams struct {
	UserID      int64
	ProblemID   pgtype.Int8
	PatternID   pgtype.Int8
	CardType    string
	Question    string
	Answer      string
	Explanation pgtype.Text
	Source      pgtype.Text
	CreatedByAi pgtype.Bool
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.UserID,
		arg.ProblemID,
		arg.PatternID,
		arg.CardType,
		arg.Question,
		arg.Answer,
		arg.Explanation,
		arg.Source,
		arg.CreatedByAi,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.PatternID,
		&i.Type,
		&i.Question,
		&i.Answer,
		&i.Explanation,
		&i.Source,
		&i.CreatedByAi,
		&i.CreatedAt,
		&i.AiPromptVersion,
	)
	return i, err
}

const createCardReviewSchedule = `-- name: CreateCardReviewSchedule :one
INSERT INTO review_schedules (
    user_id, card_id, next_review_at, interval_days,
    ease, stability, difficulty, review_count, algorithm
)
VALUES ($1, $2, $3, 0, 2.5, 0.1, 5.0, 0, 'fsrs')
ON CONFLICT (user_id, card_id) WHERE card_id IS NOT NULL DO UPDATE
SET updated_at = review_schedules.updated_at
RETURNING id
`

type CreateCardReviewScheduleParams struct {
	UserID       int64
	CardID       pgtype.Int8
	NextReviewAt pgtype.Timestamptz
}

func (q *Queries) CreateCardReviewSchedule(ctx context.Context, arg CreateCardReviewScheduleParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCardReviewSchedule, arg.UserID, arg.CardID, arg.NextReviewAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCard = `-- name: DeleteCard :execrows
DELETE FROM cards
WHERE id = $1::bigint AND user_id = $2::bigint
`

type DeleteCardParams struct {
	CardID int64
	UserID int64
}

func (q *Queries) DeleteCard(ctx context.Context, arg DeleteCardParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCard, arg.CardID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccessibleCard = `-- name: GetAccessibleCard :one
SELECT c.id
FROM cards c
WHERE c.id = $1::bigint
  AND (
    c.user_id = $2::bigint
    OR (
        c.user_id IS NULL
        AND (
            c.created_by_ai IS NOT TRUE
            OR c.problem_id IS NULL
            OR EXISTS (
                SELECT 1
                FROM user_problem_progress upp
                WHERE upp.user_id = $2::bigint
                  AND upp.problem_id = c.problem_id
                  AND upp.status IN ('solved', 'reviewing')
            )
        )
    )
    OR EXISTS (
        SELECT 1
        FROM review_schedules rs
        WHERE rs.user_id = $2::bigint AND rs.card_id = c.id
    )
  )
`

type GetAccessibleCardParams struct {
	CardID int64
	UserID int64
}

func (q *Queries) GetAccessibleCard(ctx context.Context, arg GetAccessibleCardParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAccessibleCard, arg.CardID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCardByID = `-- name: GetCardByID :one
SELECT c.id, c.user_id, c.problem_id, c.pattern_id, c.type, c.question, c.answer,
       c.explanation, c.source, c.created_by_ai, c.created_at,
       p.title AS problem_title, p.url AS problem_url, pat.name AS pattern_name
FROM cards c
LEFT JOIN problems p   ON p.id   = c.problem_id
LEFT JOIN patterns pat ON pat.id = c.pattern_id
WHERE c.id = $1::bigint AND c.user_id = $2::bigint
`

type GetCardByIDParams struct {
	CardID int64
	UserID int64
}

type GetCardByIDRow struct {
	ID           int64
	UserID       pgtype.Int8
	ProblemID    pgtype.Int8
	PatternID    pgtype.Int8
	Type         string
	Question     string
	Answer       string
	Explanation  pgtype.Text
	Source       pgtype.Text
	CreatedByAi  pgtype.Bool
	CreatedAt    pgtype.Timestamptz
	ProblemTitle pgtype.Text
	ProblemUrl   pgtype.Text
	PatternName  pgtype.Text
}

func (q *Queries) GetCardByID(ctx context.Context, arg GetCardByIDParams) (GetCardByIDRow, error) {
	row := q.db.QueryRow(ctx, getCardByID, arg.CardID, arg.UserID)
	var i GetCardByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.PatternID,
		&i.Type,
		&i.Question,
		&i.Answer,
		&i.Explanation,
		&i.Source,
		&i.CreatedByAi,
		&i.CreatedAt,
		&i.ProblemTitle,
		&i.ProblemUrl,
		&i.PatternName,
	)
	return i, err
}

const getCardReviewSchedule = `-- name: GetCardReviewSchedule :one
SELECT id
FROM review_schedules
WHERE user_id = $1 AND card_id = $2
ORDER BY id ASC
LIMIT 1
`

type GetCardReviewScheduleParams struct {
	UserID int64
	CardID pgtype.Int8
}

func (q *Queries) GetCardReviewSchedule(ctx context.Context, arg GetCardReviewScheduleParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCardReviewSchedule, arg.UserID, arg.CardID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCardSession = `-- name: ListCardSession :many
SELECT
    c.id,
    c.type,
    c.question,
    c.answer,
    c.created_by_ai,
    c.created_at,
    CASE
        WHEN c.problem_id IS NOT NULL THEN 'problem'
        WHEN c.pattern_id IS NOT NULL THEN 'pattern'
        ELSE 'custom'
    END::text AS source_entity_type,
    COALESCE(c.problem_id, c.pattern_id) AS source_entity_id,
    COALESCE(
        NULLIF(concat_ws(' · ', NULLIF(p.title, ''), NULLIF(COALESCE(cpt.name, rpt.name), '')), ''),
        NULLIF(cpt.name, ''),
        NULLIF(c.source, ''),
        'custom card'
    )::text AS source_label,
    COALESCE(rs.id, 0)::bigint AS schedule_id,
    rs.next_review_at,
    rs.last_rating,
    COALESCE(rs.review_count, 0)::integer AS review_count,
    COALESCE(rs.state, 0)::integer AS review_state
FROM cards c
LEFT JOIN LATERAL (
    SELECT id, next_review_at, last_rating, review_count, state
    FROM review_schedules
    WHERE user_id = $1::bigint AND card_id = c.id
    ORDER BY next_review_at ASC, id ASC
    LIMIT 1
) rs ON true
LEFT JOIN problems p ON p.id = c.problem_id
LEFT JOIN patterns cpt ON cpt.id = c.pattern_id
LEFT JOIN roadmap_items ri ON ri.problem_id = c.problem_id AND ri.roadmap_code = 'neetcode_150'
LEFT JOIN patterns rpt ON rpt.id = ri.pattern_id
WHERE (
    c.user_id = $1::bigint
    OR (
        c.user_id IS NULL
        AND (
            c.created_by_ai IS NOT TRUE
            OR c.problem_id IS NULL
            OR EXISTS (
                SELECT 1 FROM user_problem_progress upp
                WHERE upp.user_id = $1::bigint
                  AND upp.problem_id = c.problem_id
                  AND upp.status IN ('solved', 'reviewing')
            )
        )
    )
    OR rs.id IS NOT NULL
  )
  AND (
    $2::text = ''
    OR cpt.code = $2::text
    OR rpt.code = $2::text
  )
  AND (
    ($3::text = 'due' AND rs.next_review_at <= NOW())
    OR ($3::text = 'hard_normal' AND rs.last_rating IN ('hard', 'normal'))
    OR ($3::text = 'all')
  )
ORDER BY
    CASE
        WHEN rs.next_review_at <= NOW() THEN 0
        WHEN rs.id IS NULL THEN 1
        ELSE 2
    END,
    rs.next_review_at ASC NULLS LAST,
    c.created_at DESC,
    c.id DESC
LIMIT $4::integer
`

type ListCardSessionParams struct {
	UserID      int64
	PatternCode string
	Scope       string
	CardLimit   int32
}

type ListCardSessionRow struct {
	ID               int64
	Type             string
	Question         string
	Answer           string
	CreatedByAi      pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	SourceEntityType string
	SourceEntityID   pgtype.Int8
	SourceLabel      string
	ScheduleID       int64
	NextReviewAt     pgtype.Timestamptz
	LastRating       pgtype.Text
	ReviewCount      int32
	ReviewState      int32
}

func (q *Queries) ListCardSession(ctx context.Context, arg ListCardSessionParams) ([]ListCardSessionRow, error) {
	rows, err := q.db.Query(ctx, listCardSession,
		arg.UserID,
		arg.PatternCode,
		arg.Scope,
		arg.CardLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardSessionRow
	for rows.Next() {
		var i ListCardSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Question,
			&i.Answer,
			&i.CreatedByAi,
			&i.CreatedAt,
			&i.SourceEntityType,
			&i.SourceEntityID,
			&i.SourceLabel,
			&i.ScheduleID,
			&i.NextReviewAt,
			&i.LastRating,
			&i.ReviewCount,
			&i.ReviewState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsByProblem = `-- name: ListCardsByProblem :many
SELECT
    c.id,
    c.type,
    c.question,
    c.answer,
    c.created_by_ai,
    c.created_at,
    'problem'::text AS source_entity_type,
    c.problem_id AS source_entity_id,
    COALESCE(NULLIF(p.title, ''), 'custom card')::text AS source_label,
    COALESCE(rs.id, 0)::bigint AS schedule_id,
    rs.next_review_at,
    rs.last_rating,
    COALESCE(rs.review_count, 0)::integer AS review_count,
    COALESCE(rs.state, 0)::integer AS review_state
FROM cards c
LEFT JOIN LATERAL (
    SELECT id, next_review_at, last_rating, review_count, state
    FROM review_schedules
    WHERE user_id = $1::bigint AND card_id = c.id
    ORDER BY next_review_at ASC, id ASC
    LIMIT 1
) rs ON true
LEFT JOIN problems p ON p.id = c.problem_id
WHERE c.problem_id = $2::bigint
  AND (c.user_id = $1::bigint OR c.user_id IS NULL)
ORDER BY c.created_at ASC, c.id ASC
`

type ListCardsByProblemParams struct {
	UserID    int64
	ProblemID int64
}

type ListCardsByProblemRow struct {
	ID               int64
	Type             string
	Question         string
	Answer           string
	CreatedByAi      pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	SourceEntityType string
	SourceEntityID   pgtype.Int8
	SourceLabel      string
	ScheduleID       int64
	NextReviewAt     pgtype.Timestamptz
	LastRating       pgtype.Text
	ReviewCount      int32
	ReviewState      int32
}

// Cards visible to the user for one problem: their own cards plus global
// seed/AI cards (user_id IS NULL). Used by GET /me/problems/{id}/cards.
func (q *Queries) ListCardsByProblem(ctx context.Context, arg ListCardsByProblemParams) ([]ListCardsByProblemRow, error) {
	rows, err := q.db.Query(ctx, listCardsByProblem, arg.UserID, arg.ProblemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardsByProblemRow
	for rows.Next() {
		var i ListCardsByProblemRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Question,
			&i.Answer,
			&i.CreatedByAi,
			&i.CreatedAt,
			&i.SourceEntityType,
			&i.SourceEntityID,
			&i.SourceLabel,
			&i.ScheduleID,
			&i.NextReviewAt,
			&i.LastRating,
			&i.ReviewCount,
			&i.ReviewState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCards = `-- name: ListUserCards :many
SELECT
    c.id,
    c.type,
    c.question,
    c.answer,
    c.created_by_ai,
    c.created_at,
    CASE
        WHEN c.problem_id IS NOT NULL THEN 'problem'
        WHEN c.pattern_id IS NOT NULL THEN 'pattern'
        ELSE 'custom'
    END::text AS source_entity_type,
    COALESCE(c.problem_id, c.pattern_id) AS source_entity_id,
    COALESCE(
        NULLIF(concat_ws(' · ', NULLIF(p.title, ''), NULLIF(COALESCE(cpt.name, rpt.name), '')), ''),
        NULLIF(cpt.name, ''),
        NULLIF(c.source, ''),
        'custom card'
    )::text AS source_label,
    COALESCE(rs.id, 0)::bigint AS schedule_id,
    rs.next_review_at,
    rs.last_rating,
    COALESCE(rs.review_count, 0)::integer AS review_count,
    COALESCE(rs.state, 0)::integer AS review_state
FROM cards c
LEFT JOIN LATERAL (
    SELECT id, next_review_at, last_rating, review_count, state
    FROM review_schedules
    WHERE user_id = $1::bigint AND card_id = c.id
    ORDER BY next_review_at ASC, id ASC
    LIMIT 1
) rs ON true
LEFT JOIN problems p ON p.id = c.problem_id
LEFT JOIN patterns cpt ON cpt.id = c.pattern_id
LEFT JOIN roadmap_items ri ON ri.problem_id = c.problem_id AND ri.roadmap_code = 'neetcode_150'
LEFT JOIN patterns rpt ON rpt.id = ri.pattern_id
WHERE (
    c.user_id = $1::bigint
    OR (
        c.user_id IS NULL
        AND (
            c.created_by_ai IS NOT TRUE
            OR c.problem_id IS NULL
            OR EXISTS (
                SELECT 1 FROM user_problem_progress upp
                WHERE upp.user_id = $1::bigint
                  AND upp.problem_id = c.problem_id
                  AND upp.status IN ('solved', 'reviewing')
            )
        )
    )
    OR rs.id IS NOT NULL
  )
  AND ($2::text = '' OR c.type = $2::text)
  AND (
    $3::text = ''
    OR cpt.code = $3::text
    OR rpt.code = $3::text
  )
  AND (c.created_at, c.id) < ($4::timestamptz, $5::bigint)
ORDER BY c.created_at DESC, c.id DESC
LIMIT $6::integer
`

type ListUserCardsParams struct {
	UserID          int64
	CardType        string
	PatternCode     string
	CursorCreatedAt pgtype.Timestamptz
	CursorID        int64
	LimitRows       int32
}

type ListUserCardsRow struct {
	ID               int64
	Type             string
	Question         string
	Answer           string
	CreatedByAi      pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	SourceEntityType string
	SourceEntityID   pgtype.Int8
	SourceLabel      string
	ScheduleID       int64
	NextReviewAt     pgtype.Timestamptz
	LastRating       pgtype.Text
	ReviewCount      int32
	ReviewState      int32
}

func (q *Queries) ListUserCards(ctx context.Context, arg ListUserCardsParams) ([]ListUserCardsRow, error) {
	rows, err := q.db.Query(ctx, listUserCards,
		arg.UserID,
		arg.CardType,
		arg.PatternCode,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserCardsRow
	for rows.Next() {
		var i ListUserCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Question,
			&i.Answer,
			&i.CreatedByAi,
			&i.CreatedAt,
			&i.SourceEntityType,
			&i.SourceEntityID,
			&i.SourceLabel,
			&i.ScheduleID,
			&i.NextReviewAt,
			&i.LastRating,
			&i.ReviewCount,
			&i.ReviewState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards
SET
    type        = COALESCE($1, type),
    question    = COALESCE($2, question),
    answer      = COALESCE($3, answer),
    explanation = COALESCE($4, explanation),
    source      = COALESCE($5, source)
WHERE id = $6::bigint AND user_id = $7::bigint
RETURNING id, user_id, problem_id, pattern_id, type, question, answer, explanation, source, created_by_ai, created_at, ai_prompt_version
`

type UpdateCardParams struct {
	CardType    pgtype.Text
	Question    pgtype.Text
	Answer      pgtype.Text
	Explanation pgtype.Text
	Source      pgtype.Text
	CardID      int64
	UserID      int64
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.CardType,
		arg.Question,
		arg.Answer,
		arg.Explanation,
		arg.Source,
		arg.CardID,
		arg.UserID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.PatternID,
		&i.Type,
		&i.Question,
		&i.Answer,
		&i.Explanation,
		&i.Source,
		&i.CreatedByAi,
		&i.CreatedAt,
		&i.AiPromptVersion,
	)
	return i, err
}

const upsertGeneratedCard = `-- name: UpsertGeneratedCard :one
INSERT INTO cards (problem_id, type, question, answer, explanation, created_by_ai, ai_prompt_version)
VALUES (
    $1::bigint,
    $2,
    $3,
    $4,
    $5,
    TRUE,
    $6
)
ON CONFLICT (problem_id, type, ai_prompt_version) WHERE user_id IS NULL AND created_by_ai = TRUE AND problem_id IS NOT NULL
DO UPDATE SET
    question    = EXCLUDED.question,
    answer      = EXCLUDED.answer,
    explanation = EXCLUDED.explanation
RETURNING id
`

type UpsertGeneratedCardParams struct {
	ProblemID       int64
	CardType        string
	Question        string
	Answer          string
	Explanation     pgtype.Text
	AiPromptVersion pgtype.Text
}

// Idempotent insert for one AI-generated global card. Concurrent generations
// for the same problem+type+prompt_version converge on cards_ai_global_unique_idx.
func (q *Queries) UpsertGeneratedCard(ctx context.Context, arg UpsertGeneratedCardParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertGeneratedCard,
		arg.ProblemID,
		arg.CardType,
		arg.Question,
		arg.Answer,
		arg.Explanation,
		arg.AiPromptVersion,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
