// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package db

import (
	"context"
)

const searchCompanies = `-- name: SearchCompanies :many
SELECT code, name
FROM companies
WHERE name ILIKE '%' || $1::text || '%'
ORDER BY
    (name ILIKE $1::text || '%') DESC,
    name
LIMIT $2::int
`

type SearchCompaniesParams struct {
	Query      string
	MaxResults int32
}

type SearchCompaniesRow struct {
	Code string
	Name string
}

// Autocomplete over the companies table (populated by the company-problems
// dataset seed). Prefix matches rank above substring matches.
func (q *Queries) SearchCompanies(ctx context.Context, arg SearchCompaniesParams) ([]SearchCompaniesRow, error) {
	rows, err := q.db.Query(ctx, searchCompanies, arg.Query, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCompaniesRow
	for rows.Next() {
		var i SearchCompaniesRow
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
