// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardMetrics = `-- name: GetDashboardMetrics :one
WITH settings AS (
    SELECT COALESCE(NULLIF(u.timezone, ''), 'UTC')::text AS tz
    FROM users u
    WHERE u.id = $1
),
today AS (
    SELECT (NOW() AT TIME ZONE COALESCE((SELECT tz FROM settings), 'UTC'))::date AS day
),
due AS (
    SELECT
        COUNT(*) FILTER (WHERE next_review_at <= NOW())::integer AS due_count,
        COUNT(*) FILTER (WHERE next_review_at <= NOW() AND problem_id IS NOT NULL)::integer AS due_problem_count,
        COUNT(*) FILTER (WHERE next_review_at <= NOW() AND card_id IS NOT NULL)::integer AS due_card_count,
        COUNT(*) FILTER (WHERE next_review_at <= NOW() AND pattern_id IS NOT NULL)::integer AS due_pattern_count
    FROM review_schedules
    WHERE user_id = $1
),
progress AS (
    SELECT
        COUNT(*) FILTER (
            WHERE solved_at IS NOT NULL
               OR status IN ('solved', 'reviewing')
        )::integer AS solved_count,
        COUNT(*) FILTER (
            WHERE confidence IS NOT NULL
               OR rating IS NOT NULL
               OR status IN ('in_progress', 'solved', 'reviewing')
        )::integer AS progress_count,
        ROUND(COALESCE(AVG(
            CASE
                WHEN confidence IS NOT NULL THEN LEAST(100, GREATEST(0, confidence))
                WHEN rating = 'easy' THEN 85
                WHEN rating = 'normal' THEN 65
                WHEN rating = 'hard' THEN 35
                WHEN status IN ('solved', 'reviewing') THEN 60
                WHEN status = 'in_progress' THEN 30
                ELSE 0
            END
        ) FILTER (
            WHERE confidence IS NOT NULL
               OR rating IS NOT NULL
               OR status IN ('in_progress', 'solved', 'reviewing')
        ), 0))::integer AS readiness
    FROM user_problem_progress
    WHERE user_id = $1
),
activity_days AS (
    SELECT DISTINCT activity_day
    FROM (
        SELECT (ra.created_at AT TIME ZONE COALESCE((SELECT tz FROM settings), 'UTC'))::date AS activity_day
        FROM review_attempts ra
        WHERE ra.user_id = $1
        UNION ALL
        SELECT (upp.solved_at AT TIME ZONE COALESCE((SELECT tz FROM settings), 'UTC'))::date AS activity_day
        FROM user_problem_progress upp
        WHERE upp.user_id = $1 AND upp.solved_at IS NOT NULL
    ) days
    WHERE activity_day IS NOT NULL
      AND activity_day <= (SELECT day FROM today)
),
ranked_days AS (
    SELECT
        activity_day,
        ROW_NUMBER() OVER (ORDER BY activity_day DESC)::integer AS rn
    FROM activity_days
),
streak AS (
    SELECT COUNT(*)::integer AS current_streak
    FROM ranked_days, today
    WHERE activity_day = today.day - (rn - 1)
)
SELECT
    COALESCE((SELECT due_count FROM due), 0)::integer AS due_count,
    COALESCE((SELECT due_problem_count FROM due), 0)::integer AS due_problem_count,
    COALESCE((SELECT due_card_count FROM due), 0)::integer AS due_card_count,
    COALESCE((SELECT due_pattern_count FROM due), 0)::integer AS due_pattern_count,
    COALESCE((SELECT solved_count FROM progress), 0)::integer AS solved_count,
    COALESCE((SELECT progress_count FROM progress), 0)::integer AS progress_count,
    COALESCE((SELECT readiness FROM progress), 0)::integer AS readiness,
    COALESCE((SELECT current_streak FROM streak), 0)::integer AS current_streak
`

type GetDashboardMetricsRow struct {
	DueCount        int32
	DueProblemCount int32
	DueCardCount    int32
	DuePatternCount int32
	SolvedCount     int32
	ProgressCount   int32
	Readiness       int32
	CurrentStreak   int32
}

func (q *Queries) GetDashboardMetrics(ctx context.Context, id int64) (GetDashboardMetricsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardMetrics, id)
	var i GetDashboardMetricsRow
	err := row.Scan(
		&i.DueCount,
		&i.DueProblemCount,
		&i.DueCardCount,
		&i.DuePatternCount,
		&i.SolvedCount,
		&i.ProgressCount,
		&i.Readiness,
		&i.CurrentStreak,
	)
	return i, err
}

const getDashboardNextReview = `-- name: GetDashboardNextReview :one
SELECT
    rs.id,
    CASE
        WHEN rs.problem_id IS NOT NULL THEN 'problem'
        WHEN rs.card_id IS NOT NULL THEN 'card'
        WHEN rs.pattern_id IS NOT NULL THEN 'pattern'
        ELSE 'unknown'
    END::text AS entity_type,
    COALESCE(p.title, cp.title, c.question, sp.name, 'Review')::text AS title,
    COALESCE(rp.name, sp.name, csp.name, crp.name, '')::text AS pattern_name,
    COALESCE(p.difficulty, cp.difficulty, '')::text AS difficulty,
    rs.next_review_at,
    rs.last_rating,
    COALESCE(rs.review_count, 0)::integer AS review_count
FROM review_schedules rs
LEFT JOIN problems p ON p.id = rs.problem_id
LEFT JOIN roadmap_items ri
    ON ri.problem_id = rs.problem_id AND ri.roadmap_code = 'neetcode_150'
LEFT JOIN patterns rp ON rp.id = ri.pattern_id
LEFT JOIN patterns sp ON sp.id = rs.pattern_id
LEFT JOIN cards c ON c.id = rs.card_id
LEFT JOIN patterns csp ON csp.id = c.pattern_id
LEFT JOIN problems cp ON cp.id = c.problem_id
LEFT JOIN roadmap_items cri
    ON cri.problem_id = c.problem_id AND cri.roadmap_code = 'neetcode_150'
LEFT JOIN patterns crp ON crp.id = cri.pattern_id
WHERE rs.user_id = $1
ORDER BY rs.next_review_at ASC, rs.id ASC
LIMIT 1
`

type GetDashboardNextReviewRow struct {
	ID           int64
	EntityType   string
	Title        string
	PatternName  string
	Difficulty   string
	NextReviewAt pgtype.Timestamptz
	LastRating   pgtype.Text
	ReviewCount  int32
}

func (q *Queries) GetDashboardNextReview(ctx context.Context, userID int64) (GetDashboardNextReviewRow, error) {
	row := q.db.QueryRow(ctx, getDashboardNextReview, userID)
	var i GetDashboardNextReviewRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.Title,
		&i.PatternName,
		&i.Difficulty,
		&i.NextReviewAt,
		&i.LastRating,
		&i.ReviewCount,
	)
	return i, err
}

const listDashboardActivity = `-- name: ListDashboardActivity :many
WITH settings AS (
    SELECT COALESCE(NULLIF(u.timezone, ''), 'UTC')::text AS tz
    FROM users u
    WHERE u.id = $2::bigint
),
today AS (
    SELECT (NOW() AT TIME ZONE COALESCE((SELECT tz FROM settings), 'UTC'))::date AS day
),
events AS (
    SELECT (ra.created_at AT TIME ZONE COALESCE((SELECT tz FROM settings), 'UTC'))::date AS activity_day
    FROM review_attempts ra
    WHERE ra.user_id = $2::bigint
    UNION ALL
    SELECT (upp.solved_at AT TIME ZONE COALESCE((SELECT tz FROM settings), 'UTC'))::date AS activity_day
    FROM user_problem_progress upp
    WHERE upp.user_id = $2::bigint AND upp.solved_at IS NOT NULL
)
SELECT events.activity_day::date AS day, COUNT(*)::integer AS count
FROM events, today
WHERE events.activity_day IS NOT NULL
  AND events.activity_day <= today.day
  AND events.activity_day > today.day - $1::integer
GROUP BY events.activity_day
ORDER BY events.activity_day ASC
`

type ListDashboardActivityParams struct {
	Days   int32
	UserID int64
}

type ListDashboardActivityRow struct {
	Day   pgtype.Date
	Count int32
}

// Per-day activity counts for the heatmap: review attempts + problem solves,
// bucketed by the user's timezone, newest window of sqlc.arg(days) days.
func (q *Queries) ListDashboardActivity(ctx context.Context, arg ListDashboardActivityParams) ([]ListDashboardActivityRow, error) {
	rows, err := q.db.Query(ctx, listDashboardActivity, arg.Days, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardActivityRow
	for rows.Next() {
		var i ListDashboardActivityRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardReviewPreview = `-- name: ListDashboardReviewPreview :many
SELECT
    rs.id,
    CASE
        WHEN rs.problem_id IS NOT NULL THEN 'problem'
        WHEN rs.card_id IS NOT NULL THEN 'card'
        WHEN rs.pattern_id IS NOT NULL THEN 'pattern'
        ELSE 'unknown'
    END::text AS entity_type,
    COALESCE(p.title, cp.title, c.question, sp.name, 'Review')::text AS title,
    COALESCE(rp.name, sp.name, csp.name, crp.name, '')::text AS pattern_name,
    COALESCE(p.difficulty, cp.difficulty, '')::text AS difficulty,
    rs.next_review_at,
    rs.last_rating,
    COALESCE(rs.review_count, 0)::integer AS review_count
FROM review_schedules rs
LEFT JOIN problems p ON p.id = rs.problem_id
LEFT JOIN roadmap_items ri
    ON ri.problem_id = rs.problem_id AND ri.roadmap_code = 'neetcode_150'
LEFT JOIN patterns rp ON rp.id = ri.pattern_id
LEFT JOIN patterns sp ON sp.id = rs.pattern_id
LEFT JOIN cards c ON c.id = rs.card_id
LEFT JOIN patterns csp ON csp.id = c.pattern_id
LEFT JOIN problems cp ON cp.id = c.problem_id
LEFT JOIN roadmap_items cri
    ON cri.problem_id = c.problem_id AND cri.roadmap_code = 'neetcode_150'
LEFT JOIN patterns crp ON crp.id = cri.pattern_id
WHERE rs.user_id = $1
  AND rs.next_review_at <= NOW()
ORDER BY rs.next_review_at ASC, rs.id ASC
LIMIT $2
`

type ListDashboardReviewPreviewParams struct {
	UserID int64
	Limit  int32
}

type ListDashboardReviewPreviewRow struct {
	ID           int64
	EntityType   string
	Title        string
	PatternName  string
	Difficulty   string
	NextReviewAt pgtype.Timestamptz
	LastRating   pgtype.Text
	ReviewCount  int32
}

func (q *Queries) ListDashboardReviewPreview(ctx context.Context, arg ListDashboardReviewPreviewParams) ([]ListDashboardReviewPreviewRow, error) {
	rows, err := q.db.Query(ctx, listDashboardReviewPreview, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardReviewPreviewRow
	for rows.Next() {
		var i ListDashboardReviewPreviewRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Title,
			&i.PatternName,
			&i.Difficulty,
			&i.NextReviewAt,
			&i.LastRating,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
