// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: extension.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceProblemReviewSchedule = `-- name: AdvanceProblemReviewSchedule :one
UPDATE review_schedules
SET next_review_at = $2,
    interval_days = $3,
    review_count = review_count + 1,
    last_rating = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, next_review_at
`

type AdvanceProblemReviewScheduleParams struct {
	ID           int64
	NextReviewAt pgtype.Timestamptz
	IntervalDays float64
	LastRating   pgtype.Text
}

type AdvanceProblemReviewScheduleRow struct {
	ID           int64
	NextReviewAt pgtype.Timestamptz
}

func (q *Queries) AdvanceProblemReviewSchedule(ctx context.Context, arg AdvanceProblemReviewScheduleParams) (AdvanceProblemReviewScheduleRow, error) {
	row := q.db.QueryRow(ctx, advanceProblemReviewSchedule,
		arg.ID,
		arg.NextReviewAt,
		arg.IntervalDays,
		arg.LastRating,
	)
	var i AdvanceProblemReviewScheduleRow
	err := row.Scan(&i.ID, &i.NextReviewAt)
	return i, err
}

const createProblemReviewSchedule = `-- name: CreateProblemReviewSchedule :one
INSERT INTO review_schedules (
    user_id, problem_id, next_review_at, interval_days,
    ease, stability, difficulty, review_count, last_rating, algorithm
)
VALUES ($1, $2, $3, $4, $5, $6, $7, 1, $8, $9)
RETURNING id, next_review_at
`

type CreateProblemReviewScheduleParams struct {
	UserID       int64
	ProblemID    pgtype.Int8
	NextReviewAt pgtype.Timestamptz
	IntervalDays float64
	Ease         float64
	Stability    float64
	Difficulty   float64
	LastRating   pgtype.Text
	Algorithm    pgtype.Text
}

type CreateProblemReviewScheduleRow struct {
	ID           int64
	NextReviewAt pgtype.Timestamptz
}

func (q *Queries) CreateProblemReviewSchedule(ctx context.Context, arg CreateProblemReviewScheduleParams) (CreateProblemReviewScheduleRow, error) {
	row := q.db.QueryRow(ctx, createProblemReviewSchedule,
		arg.UserID,
		arg.ProblemID,
		arg.NextReviewAt,
		arg.IntervalDays,
		arg.Ease,
		arg.Stability,
		arg.Difficulty,
		arg.LastRating,
		arg.Algorithm,
	)
	var i CreateProblemReviewScheduleRow
	err := row.Scan(&i.ID, &i.NextReviewAt)
	return i, err
}

const getPlatformByCode = `-- name: GetPlatformByCode :one
SELECT id, code, name, base_url
FROM platforms
WHERE code = $1
`

func (q *Queries) GetPlatformByCode(ctx context.Context, code string) (Platform, error) {
	row := q.db.QueryRow(ctx, getPlatformByCode, code)
	var i Platform
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.BaseUrl,
	)
	return i, err
}

const getProblemReviewSchedule = `-- name: GetProblemReviewSchedule :one
SELECT id, next_review_at, review_count
FROM review_schedules
WHERE user_id = $1 AND problem_id = $2
`

type GetProblemReviewScheduleParams struct {
	UserID    int64
	ProblemID pgtype.Int8
}

type GetProblemReviewScheduleRow struct {
	ID           int64
	NextReviewAt pgtype.Timestamptz
	ReviewCount  pgtype.Int4
}

func (q *Queries) GetProblemReviewSchedule(ctx context.Context, arg GetProblemReviewScheduleParams) (GetProblemReviewScheduleRow, error) {
	row := q.db.QueryRow(ctx, getProblemReviewSchedule, arg.UserID, arg.ProblemID)
	var i GetProblemReviewScheduleRow
	err := row.Scan(&i.ID, &i.NextReviewAt, &i.ReviewCount)
	return i, err
}

const insertExtensionEvent = `-- name: InsertExtensionEvent :one
INSERT INTO extension_events (
    user_id, platform_id, url, external_slug, title,
    event_type, rating, extension_version, event_time, idempotency_key, raw_payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id
`

type InsertExtensionEventParams struct {
	UserID           pgtype.Int8
	PlatformID       int64
	Url              string
	ExternalSlug     pgtype.Text
	Title            pgtype.Text
	EventType        string
	Rating           pgtype.Text
	ExtensionVersion pgtype.Text
	EventTime        pgtype.Timestamptz
	IdempotencyKey   pgtype.Text
	RawPayload       []byte
}

// Idempotent on idempotency_key: a replayed event inserts nothing and the
// caller detects the no-row result as a duplicate.
func (q *Queries) InsertExtensionEvent(ctx context.Context, arg InsertExtensionEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertExtensionEvent,
		arg.UserID,
		arg.PlatformID,
		arg.Url,
		arg.ExternalSlug,
		arg.Title,
		arg.EventType,
		arg.Rating,
		arg.ExtensionVersion,
		arg.EventTime,
		arg.IdempotencyKey,
		arg.RawPayload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertExtensionProblem = `-- name: UpsertExtensionProblem :one
INSERT INTO problems (platform_id, external_slug, title, url, difficulty, source_type, created_by_user_id)
VALUES ($1, $2, $3, $4, $5, 'extension', $6)
ON CONFLICT (platform_id, external_slug) DO UPDATE
    SET title = EXCLUDED.title,
        url = EXCLUDED.url,
        difficulty = COALESCE(EXCLUDED.difficulty, problems.difficulty),
        updated_at = NOW()
RETURNING id
`

type UpsertExtensionProblemParams struct {
	PlatformID      int64
	ExternalSlug    string
	Title           string
	Url             string
	Difficulty      pgtype.Text
	CreatedByUserID pgtype.Int8
}

// Find-or-create the catalog problem keyed by (platform, external slug).
func (q *Queries) UpsertExtensionProblem(ctx context.Context, arg UpsertExtensionProblemParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertExtensionProblem,
		arg.PlatformID,
		arg.ExternalSlug,
		arg.Title,
		arg.Url,
		arg.Difficulty,
		arg.CreatedByUserID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertSolvedProgress = `-- name: UpsertSolvedProgress :exec
INSERT INTO user_problem_progress (
    user_id, problem_id, status, rating, first_seen_at, solved_at, last_reviewed_at
)
VALUES ($1, $2, 'reviewing', $3, $4, $4, $4)
ON CONFLICT (user_id, problem_id) DO UPDATE
    SET status = 'reviewing',
        rating = EXCLUDED.rating,
        solved_at = COALESCE(user_problem_progress.solved_at, EXCLUDED.solved_at),
        last_reviewed_at = EXCLUDED.last_reviewed_at
`

type UpsertSolvedProgressParams struct {
	UserID      int64
	ProblemID   int64
	Rating      pgtype.Text
	FirstSeenAt pgtype.Timestamptz
}

func (q *Queries) UpsertSolvedProgress(ctx context.Context, arg UpsertSolvedProgressParams) error {
	_, err := q.db.Exec(ctx, upsertSolvedProgress,
		arg.UserID,
		arg.ProblemID,
		arg.Rating,
		arg.FirstSeenAt,
	)
	return err
}
