// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AiRequestLog struct {
	ID            int64
	UserID        pgtype.Int8
	Feature       pgtype.Text
	Provider      pgtype.Text
	Model         pgtype.Text
	InputTokens   pgtype.Int4
	OutputTokens  pgtype.Int4
	EstimatedCost pgtype.Numeric
	Status        pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type Card struct {
	ID              int64
	UserID          pgtype.Int8
	ProblemID       pgtype.Int8
	PatternID       pgtype.Int8
	Type            string
	Question        string
	Answer          string
	Explanation     pgtype.Text
	Source          pgtype.Text
	CreatedByAi     pgtype.Bool
	CreatedAt       pgtype.Timestamptz
	AiPromptVersion pgtype.Text
}

type Company struct {
	ID   int64
	Code string
	Name string
}

type CompanyProblem struct {
	CompanyID     int64
	ProblemID     int64
	EvidenceCount int32
	LastSeenAt    pgtype.Date
	SourceType    string
}

type ExtensionEvent struct {
	ID               int64
	UserID           pgtype.Int8
	PlatformID       int64
	Url              string
	ExternalSlug     pgtype.Text
	Title            pgtype.Text
	EventType        string
	Rating           pgtype.Text
	ExtensionVersion pgtype.Text
	EventTime        pgtype.Timestamptz
	IdempotencyKey   pgtype.Text
	RawPayload       []byte
	CreatedAt        pgtype.Timestamptz
}

type Pattern struct {
	ID                  int64
	Code                string
	Name                string
	Description         pgtype.Text
	ParentID            pgtype.Int8
	Techniques          []string
	RecognitionSymptoms []string
	Checklist           []string
	// Node role: pattern=legacy roadmap grouping, tool=prerequisite, family=pattern family, subpattern=learning unit.
	Kind string
	// Taxonomy release this node belongs to (NULL for legacy nodes outside the taxonomy).
	TaxonomyVersion pgtype.Text
	// Display order inside its kind for taxonomy nodes.
	Position pgtype.Int4
}

type PatternFamilySubpattern struct {
	FamilyID     int64
	SubpatternID int64
	Position     int32
}

type PatternLearningMaterial struct {
	PatternID         int64
	WhatItIs          string
	MentalModel       string
	RecognitionCues   []string
	AntiCues          []string
	CoreInvariant     string
	CanonicalSkeleton string
	CommonMistakes    []string
	// JSON array of {"title","note"} contrast pairs.
	DontConfuseWith []byte
	UpdatedAt       pgtype.Timestamptz
}

type Platform struct {
	ID      int64
	Code    string
	Name    string
	BaseUrl string
}

type Problem struct {
	ID              int64
	PlatformID      int64
	ExternalSlug    string
	Title           string
	Url             string
	Difficulty      pgtype.Text
	SourceType      pgtype.Text
	CreatedByUserID pgtype.Int8
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ExternalID      pgtype.Text
}

type ProblemSubpattern struct {
	ProblemID    int64
	SubpatternID int64
	Tier         pgtype.Text
	Position     pgtype.Int4
}

type QuizQuestion struct {
	ID            int64
	UserID        pgtype.Int8
	ProblemID     pgtype.Int8
	PatternID     pgtype.Int8
	Question      string
	Options       []byte
	CorrectOption int32
	Explanation   pgtype.Text
	Difficulty    pgtype.Text
	CreatedByAi   pgtype.Bool
	CreatedAt     pgtype.Timestamptz
}

type ReviewAttempt struct {
	ID          int64
	UserID      int64
	ProblemID   pgtype.Int8
	PatternID   pgtype.Int8
	CardID      pgtype.Int8
	Rating      string
	ReviewType  string
	DurationSec pgtype.Int4
	WasCorrect  pgtype.Bool
	CreatedAt   pgtype.Timestamptz
}

type ReviewSchedule struct {
	ID           int64
	UserID       int64
	ProblemID    pgtype.Int8
	PatternID    pgtype.Int8
	CardID       pgtype.Int8
	NextReviewAt pgtype.Timestamptz
	// Current review interval length in days.
	IntervalDays float64
	// Ease factor used by the spaced repetition algorithm.
	Ease float64
	// Memory stability coefficient used by the spaced repetition algorithm.
	Stability float64
	// Memory difficulty coefficient used by the spaced repetition algorithm.
	Difficulty  float64
	ReviewCount pgtype.Int4
	LastRating  pgtype.Text
	Algorithm   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	// FSRS card state: 0=New, 1=Learning, 2=Review, 3=Relearning
	State int16
	// Number of times the card has been forgotten (FSRS Card.Lapses).
	Lapses int32
	// Timestamp of the last review (FSRS Card.LastReview).
	LastReviewAt pgtype.Timestamptz
	// Remaining learning/relearning steps (FSRS Card.RemainingSteps).
	RemainingSteps int32
}

type RoadmapItem struct {
	RoadmapCode string
	PatternID   int64
	ProblemID   int64
	Position    int32
}

type SubpatternCompany struct {
	SubpatternID  int64
	CompanyID     int64
	Relevance     string
	Confidence    string
	EvidenceCount int32
	LastSeenAt    pgtype.Date
	SourceType    string
}

type SubpatternPrerequisite struct {
	SubpatternID int64
	ToolID       int64
}

type TaxonomyVersion struct {
	Code      string
	Title     string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID                    int64
	Email                 string
	PasswordHash          string
	Timezone              pgtype.Text
	Plan                  pgtype.Text
	InterviewDate         pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	PrepGoal              pgtype.Text
	Grade                 pgtype.Text
	TargetCompany         pgtype.Text
	TargetPosition        pgtype.Text
	OnboardingCompletedAt pgtype.Timestamptz
	NotifyReviewReminder  bool
	NotifyWeeklyDigest    bool
	NotifyEmailEnabled    bool
}

type UserProblemProgress struct {
	ID             int64
	UserID         int64
	ProblemID      int64
	Status         pgtype.Text
	Rating         pgtype.Text
	FirstSeenAt    pgtype.Timestamptz
	SolvedAt       pgtype.Timestamptz
	LastReviewedAt pgtype.Timestamptz
	Confidence     pgtype.Int4
	Note           pgtype.Text
}
