// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patterns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPatternByCode = `-- name: GetPatternByCode :one
SELECT
    id,
    code,
    name,
    description,
    techniques,
    recognition_symptoms,
    checklist
FROM patterns
WHERE code = $1
`

type GetPatternByCodeRow struct {
	ID                  int64
	Code                string
	Name                string
	Description         pgtype.Text
	Techniques          []string
	RecognitionSymptoms []string
	Checklist           []string
}

func (q *Queries) GetPatternByCode(ctx context.Context, code string) (GetPatternByCodeRow, error) {
	row := q.db.QueryRow(ctx, getPatternByCode, code)
	var i GetPatternByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Techniques,
		&i.RecognitionSymptoms,
		&i.Checklist,
	)
	return i, err
}

const listPatternExampleProblems = `-- name: ListPatternExampleProblems :many
SELECT
    p.id,
    p.title,
    p.difficulty,
    p.url
FROM roadmap_items ri
JOIN problems p ON p.id = ri.problem_id
WHERE ri.pattern_id = $1
  AND ri.roadmap_code = 'neetcode_150'
ORDER BY ri.position
LIMIT $2
`

type ListPatternExampleProblemsParams struct {
	PatternID int64
	Limit     int32
}

type ListPatternExampleProblemsRow struct {
	ID         int64
	Title      string
	Difficulty pgtype.Text
	Url        string
}

func (q *Queries) ListPatternExampleProblems(ctx context.Context, arg ListPatternExampleProblemsParams) ([]ListPatternExampleProblemsRow, error) {
	rows, err := q.db.Query(ctx, listPatternExampleProblems, arg.PatternID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatternExampleProblemsRow
	for rows.Next() {
		var i ListPatternExampleProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Difficulty,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatterns = `-- name: ListPatterns :many
SELECT
    pt.id,
    pt.code,
    pt.name,
    COALESCE(pt.description, '')::text AS description,
    pt.parent_id,
    COUNT(DISTINCT ri.problem_id)::integer AS problem_count,
    COUNT(DISTINCT upp.problem_id) FILTER (
        WHERE upp.status IN ('solving', 'solved', 'reviewing')
    )::integer AS solved_count,
    COUNT(DISTINCT rs.id) FILTER (
        WHERE rs.next_review_at <= NOW()
    )::integer AS due_count
FROM patterns pt
LEFT JOIN roadmap_items ri ON ri.pattern_id = pt.id AND ri.roadmap_code = 'neetcode_150'
LEFT JOIN user_problem_progress upp ON upp.problem_id = ri.problem_id AND upp.user_id = $1::bigint
LEFT JOIN review_schedules rs ON rs.pattern_id = pt.id AND rs.user_id = $1::bigint
GROUP BY pt.id, pt.code, pt.name, pt.description, pt.parent_id
ORDER BY pt.name ASC
`

type ListPatternsRow struct {
	ID           int64
	Code         string
	Name         string
	Description  string
	ParentID     pgtype.Int8
	ProblemCount int32
	SolvedCount  int32
	DueCount     int32
}

// All patterns with per-user progress counts for problems in neetcode_150.
func (q *Queries) ListPatterns(ctx context.Context, dollar_1 int64) ([]ListPatternsRow, error) {
	rows, err := q.db.Query(ctx, listPatterns, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatternsRow
	for rows.Next() {
		var i ListPatternsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.ParentID,
			&i.ProblemCount,
			&i.SolvedCount,
			&i.DueCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeakPatterns = `-- name: ListWeakPatterns :many
SELECT
    pt.code AS pattern_code,
    pt.name AS pattern_name,
    COUNT(*)::integer AS review_count,
    COUNT(*) FILTER (WHERE ra.rating = 'hard')::integer AS hard_count
FROM review_attempts ra
LEFT JOIN roadmap_items ri
    ON ri.problem_id = ra.problem_id AND ri.roadmap_code = 'neetcode_150'
JOIN patterns pt ON pt.id = COALESCE(ra.pattern_id, ri.pattern_id)
WHERE ra.user_id = $1
GROUP BY pt.code, pt.name
HAVING COUNT(*) FILTER (WHERE ra.rating = 'hard') > 0
ORDER BY hard_count DESC, review_count DESC, pattern_name ASC
LIMIT $2
`

type ListWeakPatternsParams struct {
	UserID int64
	Limit  int32
}

type ListWeakPatternsRow struct {
	PatternCode string
	PatternName string
	ReviewCount int32
	HardCount   int32
}

func (q *Queries) ListWeakPatterns(ctx context.Context, arg ListWeakPatternsParams) ([]ListWeakPatternsRow, error) {
	rows, err := q.db.Query(ctx, listWeakPatterns, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWeakPatternsRow
	for rows.Next() {
		var i ListWeakPatternsRow
		if err := rows.Scan(
			&i.PatternCode,
			&i.PatternName,
			&i.ReviewCount,
			&i.HardCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
