// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patterns.sql

package db

import (
	"context"
)

const listWeakPatterns = `-- name: ListWeakPatterns :many
SELECT
    pt.code AS pattern_code,
    pt.name AS pattern_name,
    COUNT(*)::integer AS review_count,
    COUNT(*) FILTER (WHERE ra.rating = 'hard')::integer AS hard_count
FROM review_attempts ra
LEFT JOIN roadmap_items ri
    ON ri.problem_id = ra.problem_id AND ri.roadmap_code = 'neetcode_150'
JOIN patterns pt ON pt.id = COALESCE(ra.pattern_id, ri.pattern_id)
WHERE ra.user_id = $1
GROUP BY pt.code, pt.name
HAVING COUNT(*) FILTER (WHERE ra.rating = 'hard') > 0
ORDER BY hard_count DESC, review_count DESC, pattern_name ASC
LIMIT $2
`

type ListWeakPatternsParams struct {
	UserID int64
	Limit  int32
}

type ListWeakPatternsRow struct {
	PatternCode string
	PatternName string
	ReviewCount int32
	HardCount   int32
}

func (q *Queries) ListWeakPatterns(ctx context.Context, arg ListWeakPatternsParams) ([]ListWeakPatternsRow, error) {
	rows, err := q.db.Query(ctx, listWeakPatterns, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWeakPatternsRow
	for rows.Next() {
		var i ListWeakPatternsRow
		if err := rows.Scan(
			&i.PatternCode,
			&i.PatternName,
			&i.ReviewCount,
			&i.HardCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
