// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: practice.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPracticeSubpattern = `-- name: AddPracticeSubpattern :exec
INSERT INTO user_practice_patterns (user_id, pattern_id)
VALUES ($1::bigint, $2::bigint)
ON CONFLICT (user_id, pattern_id) DO NOTHING
`

type AddPracticeSubpatternParams struct {
	UserID    int64
	PatternID int64
}

func (q *Queries) AddPracticeSubpattern(ctx context.Context, arg AddPracticeSubpatternParams) error {
	_, err := q.db.Exec(ctx, addPracticeSubpattern, arg.UserID, arg.PatternID)
	return err
}

const getSubpatternIDByCode = `-- name: GetSubpatternIDByCode :one
SELECT id FROM patterns
WHERE code = $1::text AND kind = 'subpattern'
`

func (q *Queries) GetSubpatternIDByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, getSubpatternIDByCode, code)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listPracticeSubpatterns = `-- name: ListPracticeSubpatterns :many

SELECT p.code, p.name, up.added_at
FROM user_practice_patterns up
JOIN patterns p ON p.id = up.pattern_id
WHERE up.user_id = $1::bigint
ORDER BY up.added_at DESC, p.name ASC
`

type ListPracticeSubpatternsRow struct {
	Code    string
	Name    string
	AddedAt pgtype.Timestamptz
}

// Практика подпаттернов: личный набор «активных» подпаттернов пользователя.
func (q *Queries) ListPracticeSubpatterns(ctx context.Context, userID int64) ([]ListPracticeSubpatternsRow, error) {
	rows, err := q.db.Query(ctx, listPracticeSubpatterns, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPracticeSubpatternsRow
	for rows.Next() {
		var i ListPracticeSubpatternsRow
		if err := rows.Scan(&i.Code, &i.Name, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePracticeSubpattern = `-- name: RemovePracticeSubpattern :execrows
DELETE FROM user_practice_patterns
WHERE user_id = $1::bigint
  AND pattern_id = (
    SELECT id FROM patterns
    WHERE code = $2::text AND kind = 'subpattern'
  )
`

type RemovePracticeSubpatternParams struct {
	UserID int64
	Code   string
}

func (q *Queries) RemovePracticeSubpattern(ctx context.Context, arg RemovePracticeSubpatternParams) (int64, error) {
	result, err := q.db.Exec(ctx, removePracticeSubpattern, arg.UserID, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeUnreviewedPracticeSchedules = `-- name: RemoveUnreviewedPracticeSchedules :execrows
DELETE FROM review_schedules rs
USING cards c, patterns p
WHERE rs.user_id = $1::bigint
  AND rs.card_id = c.id
  AND c.pattern_id = p.id
  AND p.code = $2::text
  AND p.kind = 'subpattern'
  AND COALESCE(rs.review_count, 0) = 0
  AND rs.last_review_at IS NULL
`

type RemoveUnreviewedPracticeSchedulesParams struct {
	UserID int64
	Code   string
}

// Eager schedules created by Add are disposable until the user has actually
// reviewed the card. Remove those untouched rows with the membership; keep
// reviewed schedules/history intact.
func (q *Queries) RemoveUnreviewedPracticeSchedules(ctx context.Context, arg RemoveUnreviewedPracticeSchedulesParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeUnreviewedPracticeSchedules, arg.UserID, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
