// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problems.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listUserProblems = `-- name: ListUserProblems :many
WITH scoped_problems AS (
    SELECT
        p.id,
        COALESCE(p.external_id, p.external_slug) AS external_id,
        p.title,
        p.url,
        CASE
            WHEN pl.code IN ('leetcode', 'neetcode', 'codeforces') THEN pl.code
            ELSE 'custom'
        END AS platform,
        CASE
            WHEN p.difficulty IS NULL THEN 'unknown'
            ELSE p.difficulty::text
        END AS difficulty,
        CASE
            WHEN upp.status = 'reviewing' THEN 'reviewing'
            WHEN upp.status = 'solved' THEN 'mastered'
            WHEN upp.status = 'mastered' THEN 'mastered'
            WHEN upp.status = 'skipped' THEN 'archived'
            WHEN upp.status = 'archived' THEN 'archived'
            ELSE 'saved'
        END AS status,
        pt.code AS pattern_id,
        pt.name AS pattern_name,
        rs.next_review_at,
        COALESCE(rs.last_rating, upp.rating) AS last_rating,
        upp.solved_at,
        COALESCE(p.created_at, '1970-01-01 00:00:00+00'::timestamptz) AS created_at,
        COALESCE(p.updated_at, p.created_at, '1970-01-01 00:00:00+00'::timestamptz) AS updated_at
    FROM problems p
    JOIN platforms pl ON pl.id = p.platform_id
    LEFT JOIN user_problem_progress upp
        ON upp.user_id = $6 AND upp.problem_id = p.id
    LEFT JOIN LATERAL (
        SELECT next_review_at, last_rating
        FROM review_schedules
        WHERE user_id = $6
          AND problem_id = p.id
        ORDER BY next_review_at ASC, id ASC
        LIMIT 1
    ) rs ON TRUE
    LEFT JOIN roadmap_items ri
        ON ri.problem_id = p.id AND ri.roadmap_code = 'neetcode_150'
    LEFT JOIN patterns pt ON pt.id = ri.pattern_id
    WHERE upp.user_id IS NOT NULL
       OR p.created_by_user_id = $6
       OR rs.next_review_at IS NOT NULL
)
SELECT
    id,
    external_id,
    title,
    url,
    platform,
    difficulty,
    pattern_id,
    pattern_name,
    status,
    next_review_at,
    last_rating,
    solved_at,
    created_at,
    updated_at
FROM scoped_problems
WHERE ($1::text = '' OR status = $1::text)
  AND ($2::text = '' OR platform = $2::text)
  AND (created_at, id) < ($3::timestamptz, $4::bigint)
ORDER BY created_at DESC, id DESC
LIMIT $5::int
`

type ListUserProblemsParams struct {
	Status          string
	Platform        string
	CursorCreatedAt pgtype.Timestamptz
	CursorID        int64
	LimitRows       int32
	UserID          int64
}

type ListUserProblemsRow struct {
	ID           int64
	ExternalID   string
	Title        string
	Url          string
	Platform     string
	Difficulty   string
	PatternID    pgtype.Text
	PatternName  pgtype.Text
	Status       string
	NextReviewAt pgtype.Timestamptz
	LastRating   pgtype.Text
	SolvedAt     pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListUserProblems(ctx context.Context, arg ListUserProblemsParams) ([]ListUserProblemsRow, error) {
	rows, err := q.db.Query(ctx, listUserProblems,
		arg.Status,
		arg.Platform,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitRows,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserProblemsRow
	for rows.Next() {
		var i ListUserProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Platform,
			&i.Difficulty,
			&i.PatternID,
			&i.PatternName,
			&i.Status,
			&i.NextReviewAt,
			&i.LastRating,
			&i.SolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
