// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quiz.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getQuizQuestion = `-- name: GetQuizQuestion :one
SELECT
    qq.id,
    qq.question,
    qq.options,
    qq.correct_option,
    qq.explanation,
    qq.difficulty,
    qq.created_by_ai,
    qq.created_at,
    p.id    AS problem_id,
    p.title AS problem_title,
    pat.id   AS pattern_id,
    pat.name AS pattern_name
FROM quiz_questions qq
LEFT JOIN problems p   ON p.id   = qq.problem_id
LEFT JOIN patterns pat ON pat.id = qq.pattern_id
WHERE qq.id = $1::bigint AND qq.user_id = $2::bigint
`

type GetQuizQuestionParams struct {
	QuestionID int64
	UserID     int64
}

type GetQuizQuestionRow struct {
	ID            int64
	Question      string
	Options       []byte
	CorrectOption int32
	Explanation   pgtype.Text
	Difficulty    pgtype.Text
	CreatedByAi   pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	ProblemID     pgtype.Int8
	ProblemTitle  pgtype.Text
	PatternID     pgtype.Int8
	PatternName   pgtype.Text
}

// Returns a single question with the correct_option for answer verification.
func (q *Queries) GetQuizQuestion(ctx context.Context, arg GetQuizQuestionParams) (GetQuizQuestionRow, error) {
	row := q.db.QueryRow(ctx, getQuizQuestion, arg.QuestionID, arg.UserID)
	var i GetQuizQuestionRow
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.Options,
		&i.CorrectOption,
		&i.Explanation,
		&i.Difficulty,
		&i.CreatedByAi,
		&i.CreatedAt,
		&i.ProblemID,
		&i.ProblemTitle,
		&i.PatternID,
		&i.PatternName,
	)
	return i, err
}

const listQuizSession = `-- name: ListQuizSession :many
SELECT
    qq.id,
    qq.question,
    qq.options,
    qq.difficulty,
    qq.created_by_ai,
    qq.created_at,
    p.id    AS problem_id,
    p.title AS problem_title,
    pat.id   AS pattern_id,
    pat.name AS pattern_name
FROM quiz_questions qq
LEFT JOIN problems p   ON p.id   = qq.problem_id
LEFT JOIN patterns pat ON pat.id = qq.pattern_id
WHERE qq.user_id = $1::bigint
  AND NOT EXISTS (
    SELECT 1
    FROM quiz_answers qa
    WHERE qa.user_id = $1::bigint
      AND qa.question_id = qq.id
  )
ORDER BY qq.created_at DESC
LIMIT $2::int
`

type ListQuizSessionParams struct {
	UserID       int64
	SessionLimit int32
}

type ListQuizSessionRow struct {
	ID           int64
	Question     string
	Options      []byte
	Difficulty   pgtype.Text
	CreatedByAi  pgtype.Bool
	CreatedAt    pgtype.Timestamptz
	ProblemID    pgtype.Int8
	ProblemTitle pgtype.Text
	PatternID    pgtype.Int8
	PatternName  pgtype.Text
}

// Returns the user's quiz questions ordered by creation date (newest first).
// Caller passes a limit for session size.
func (q *Queries) ListQuizSession(ctx context.Context, arg ListQuizSessionParams) ([]ListQuizSessionRow, error) {
	rows, err := q.db.Query(ctx, listQuizSession, arg.UserID, arg.SessionLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuizSessionRow
	for rows.Next() {
		var i ListQuizSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.Question,
			&i.Options,
			&i.Difficulty,
			&i.CreatedByAi,
			&i.CreatedAt,
			&i.ProblemID,
			&i.ProblemTitle,
			&i.PatternID,
			&i.PatternName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordQuizAnswer = `-- name: RecordQuizAnswer :execrows
INSERT INTO quiz_answers (user_id, question_id, selected_option, was_correct)
VALUES ($1::bigint, $2::bigint,
        $3::int, $4::bool)
ON CONFLICT (user_id, question_id) DO NOTHING
`

type RecordQuizAnswerParams struct {
	UserID         int64
	QuestionID     int64
	SelectedOption int32
	WasCorrect     bool
}

// Фиксирует ответ пользователя. Анти-чит: UNIQUE (user_id, question_id) +
// ON CONFLICT DO NOTHING делает вставку атомарной — количество затронутых
// строк (1 = первый ответ записан, 0 = пара уже существует / повтор) заменяет
// отдельную проверку IsAnswered и не имеет TOCTOU-окна.
func (q *Queries) RecordQuizAnswer(ctx context.Context, arg RecordQuizAnswerParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordQuizAnswer,
		arg.UserID,
		arg.QuestionID,
		arg.SelectedOption,
		arg.WasCorrect,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
