// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReviewAttempt = `-- name: CreateReviewAttempt :one
INSERT INTO review_attempts (user_id, problem_id, pattern_id, rating, review_type, duration_sec, was_correct)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, problem_id, pattern_id, rating, review_type, duration_sec, was_correct, created_at
`

type CreateReviewAttemptParams struct {
	UserID      int64
	ProblemID   pgtype.Int8
	PatternID   pgtype.Int8
	Rating      string
	ReviewType  string
	DurationSec pgtype.Int4
	WasCorrect  pgtype.Bool
}

func (q *Queries) CreateReviewAttempt(ctx context.Context, arg CreateReviewAttemptParams) (ReviewAttempt, error) {
	row := q.db.QueryRow(ctx, createReviewAttempt,
		arg.UserID,
		arg.ProblemID,
		arg.PatternID,
		arg.Rating,
		arg.ReviewType,
		arg.DurationSec,
		arg.WasCorrect,
	)
	var i ReviewAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.PatternID,
		&i.Rating,
		&i.ReviewType,
		&i.DurationSec,
		&i.WasCorrect,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewScheduleByID = `-- name: GetReviewScheduleByID :one
SELECT id, user_id, problem_id, pattern_id, card_id, next_review_at,
       interval_days, stability, difficulty, review_count, last_rating,
       state, lapses, last_review_at, remaining_steps
FROM review_schedules
WHERE id = $1 AND user_id = $2
`

type GetReviewScheduleByIDParams struct {
	ID     int64
	UserID int64
}

type GetReviewScheduleByIDRow struct {
	ID             int64
	UserID         int64
	ProblemID      pgtype.Int8
	PatternID      pgtype.Int8
	CardID         pgtype.Int8
	NextReviewAt   pgtype.Timestamptz
	IntervalDays   float64
	Stability      float64
	Difficulty     float64
	ReviewCount    pgtype.Int4
	LastRating     pgtype.Text
	State          int16
	Lapses         int32
	LastReviewAt   pgtype.Timestamptz
	RemainingSteps int32
}

func (q *Queries) GetReviewScheduleByID(ctx context.Context, arg GetReviewScheduleByIDParams) (GetReviewScheduleByIDRow, error) {
	row := q.db.QueryRow(ctx, getReviewScheduleByID, arg.ID, arg.UserID)
	var i GetReviewScheduleByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.PatternID,
		&i.CardID,
		&i.NextReviewAt,
		&i.IntervalDays,
		&i.Stability,
		&i.Difficulty,
		&i.ReviewCount,
		&i.LastRating,
		&i.State,
		&i.Lapses,
		&i.LastReviewAt,
		&i.RemainingSteps,
	)
	return i, err
}

const getReviewStats = `-- name: GetReviewStats :one
SELECT
    COUNT(*)::integer AS total_reviews,
    COUNT(*) FILTER (WHERE state = 0)::integer AS new_cards,
    COUNT(*) FILTER (WHERE state IN (1, 3))::integer AS learning_cards,
    COUNT(*) FILTER (WHERE state = 2)::integer AS review_cards
FROM review_schedules
WHERE user_id = $1
`

type GetReviewStatsRow struct {
	TotalReviews  int32
	NewCards      int32
	LearningCards int32
	ReviewCards   int32
}

func (q *Queries) GetReviewStats(ctx context.Context, userID int64) (GetReviewStatsRow, error) {
	row := q.db.QueryRow(ctx, getReviewStats, userID)
	var i GetReviewStatsRow
	err := row.Scan(
		&i.TotalReviews,
		&i.NewCards,
		&i.LearningCards,
		&i.ReviewCards,
	)
	return i, err
}

const getTodayReviews = `-- name: GetTodayReviews :many
SELECT rs.id, rs.user_id, rs.problem_id, rs.pattern_id, rs.card_id, rs.next_review_at,
       rs.interval_days, rs.stability, rs.difficulty, rs.review_count,
       rs.last_rating, rs.state, rs.lapses, rs.last_review_at, rs.remaining_steps,
       p.title AS problem_title, p.url AS problem_url,
       pt.name AS pattern_title
FROM review_schedules rs
LEFT JOIN problems p ON p.id = rs.problem_id
LEFT JOIN patterns pt ON pt.id = rs.pattern_id
WHERE rs.user_id = $1 AND rs.next_review_at <= NOW()
ORDER BY rs.next_review_at ASC
LIMIT $2
`

type GetTodayReviewsParams struct {
	UserID int64
	Limit  int32
}

type GetTodayReviewsRow struct {
	ID             int64
	UserID         int64
	ProblemID      pgtype.Int8
	PatternID      pgtype.Int8
	CardID         pgtype.Int8
	NextReviewAt   pgtype.Timestamptz
	IntervalDays   float64
	Stability      float64
	Difficulty     float64
	ReviewCount    pgtype.Int4
	LastRating     pgtype.Text
	State          int16
	Lapses         int32
	LastReviewAt   pgtype.Timestamptz
	RemainingSteps int32
	ProblemTitle   pgtype.Text
	ProblemUrl     pgtype.Text
	PatternTitle   pgtype.Text
}

func (q *Queries) GetTodayReviews(ctx context.Context, arg GetTodayReviewsParams) ([]GetTodayReviewsRow, error) {
	rows, err := q.db.Query(ctx, getTodayReviews, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTodayReviewsRow
	for rows.Next() {
		var i GetTodayReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.PatternID,
			&i.CardID,
			&i.NextReviewAt,
			&i.IntervalDays,
			&i.Stability,
			&i.Difficulty,
			&i.ReviewCount,
			&i.LastRating,
			&i.State,
			&i.Lapses,
			&i.LastReviewAt,
			&i.RemainingSteps,
			&i.ProblemTitle,
			&i.ProblemUrl,
			&i.PatternTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgressConfidence = `-- name: UpdateProgressConfidence :exec
UPDATE user_problem_progress
SET confidence = CASE
    WHEN confidence + $3::int < 0 THEN 0
    WHEN confidence + $3::int > 100 THEN 100
    ELSE confidence + $3::int
END
WHERE user_id = $1 AND problem_id = $2
`

type UpdateProgressConfidenceParams struct {
	UserID    int64
	ProblemID int64
	Column3   int32
}

func (q *Queries) UpdateProgressConfidence(ctx context.Context, arg UpdateProgressConfidenceParams) error {
	_, err := q.db.Exec(ctx, updateProgressConfidence, arg.UserID, arg.ProblemID, arg.Column3)
	return err
}

const updateReviewSchedule = `-- name: UpdateReviewSchedule :one
UPDATE review_schedules
SET next_review_at = $2, interval_days = $3, stability = $4, difficulty = $5,
    review_count = $6, last_rating = $7, state = $8, lapses = $9,
    last_review_at = $10, remaining_steps = $11, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, problem_id, pattern_id, card_id, next_review_at,
          interval_days, stability, difficulty, review_count, last_rating,
          state, lapses, last_review_at, remaining_steps
`

type UpdateReviewScheduleParams struct {
	ID             int64
	NextReviewAt   pgtype.Timestamptz
	IntervalDays   float64
	Stability      float64
	Difficulty     float64
	ReviewCount    pgtype.Int4
	LastRating     pgtype.Text
	State          int16
	Lapses         int32
	LastReviewAt   pgtype.Timestamptz
	RemainingSteps int32
}

type UpdateReviewScheduleRow struct {
	ID             int64
	UserID         int64
	ProblemID      pgtype.Int8
	PatternID      pgtype.Int8
	CardID         pgtype.Int8
	NextReviewAt   pgtype.Timestamptz
	IntervalDays   float64
	Stability      float64
	Difficulty     float64
	ReviewCount    pgtype.Int4
	LastRating     pgtype.Text
	State          int16
	Lapses         int32
	LastReviewAt   pgtype.Timestamptz
	RemainingSteps int32
}

func (q *Queries) UpdateReviewSchedule(ctx context.Context, arg UpdateReviewScheduleParams) (UpdateReviewScheduleRow, error) {
	row := q.db.QueryRow(ctx, updateReviewSchedule,
		arg.ID,
		arg.NextReviewAt,
		arg.IntervalDays,
		arg.Stability,
		arg.Difficulty,
		arg.ReviewCount,
		arg.LastRating,
		arg.State,
		arg.Lapses,
		arg.LastReviewAt,
		arg.RemainingSteps,
	)
	var i UpdateReviewScheduleRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.PatternID,
		&i.CardID,
		&i.NextReviewAt,
		&i.IntervalDays,
		&i.Stability,
		&i.Difficulty,
		&i.ReviewCount,
		&i.LastRating,
		&i.State,
		&i.Lapses,
		&i.LastReviewAt,
		&i.RemainingSteps,
	)
	return i, err
}
