// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roadmap.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearRoadmapTarget = `-- name: ClearRoadmapTarget :exec
UPDATE users
SET target_company = NULL, interview_date = NULL, target_topics = '{}', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClearRoadmapTarget(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearRoadmapTarget, id)
	return err
}

const getRoadmapUserTarget = `-- name: GetRoadmapUserTarget :one
SELECT target_company, interview_date, target_topics
FROM users
WHERE id = $1
`

type GetRoadmapUserTargetRow struct {
	TargetCompany pgtype.Text
	InterviewDate pgtype.Timestamptz
	TargetTopics  []string
}

func (q *Queries) GetRoadmapUserTarget(ctx context.Context, id int64) (GetRoadmapUserTargetRow, error) {
	row := q.db.QueryRow(ctx, getRoadmapUserTarget, id)
	var i GetRoadmapUserTargetRow
	err := row.Scan(&i.TargetCompany, &i.InterviewDate, &i.TargetTopics)
	return i, err
}

const listUserRoadmapItems = `-- name: ListUserRoadmapItems :many
SELECT
    ri.position,
    pt.code AS pattern_code,
    pt.name AS pattern_name,
    p.id AS problem_id,
    p.external_id,
    p.external_slug,
    p.title,
    p.url,
    p.difficulty,
    COALESCE(upp.status, 'not_started')::text AS status,
    upp.rating,
    upp.confidence
FROM roadmap_items ri
JOIN patterns pt ON pt.id = ri.pattern_id
JOIN problems p ON p.id = ri.problem_id
LEFT JOIN user_problem_progress upp
    ON upp.problem_id = p.id AND upp.user_id = $2
WHERE ri.roadmap_code = $1
ORDER BY ri.position ASC
`

type ListUserRoadmapItemsParams struct {
	RoadmapCode string
	UserID      int64
}

type ListUserRoadmapItemsRow struct {
	Position     int32
	PatternCode  string
	PatternName  string
	ProblemID    int64
	ExternalID   pgtype.Text
	ExternalSlug string
	Title        string
	Url          string
	Difficulty   pgtype.Text
	Status       string
	Rating       pgtype.Text
	Confidence   pgtype.Int4
}

func (q *Queries) ListUserRoadmapItems(ctx context.Context, arg ListUserRoadmapItemsParams) ([]ListUserRoadmapItemsRow, error) {
	rows, err := q.db.Query(ctx, listUserRoadmapItems, arg.RoadmapCode, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRoadmapItemsRow
	for rows.Next() {
		var i ListUserRoadmapItemsRow
		if err := rows.Scan(
			&i.Position,
			&i.PatternCode,
			&i.PatternName,
			&i.ProblemID,
			&i.ExternalID,
			&i.ExternalSlug,
			&i.Title,
			&i.Url,
			&i.Difficulty,
			&i.Status,
			&i.Rating,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
