// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roadmaps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRoadmapItems = `-- name: ListRoadmapItems :many
SELECT
    ri.position,
    pt.code AS pattern_code,
    pt.name AS pattern_name,
    p.id AS problem_id,
    p.external_id,
    p.external_slug,
    p.title,
    p.url,
    p.difficulty
FROM roadmap_items ri
JOIN patterns pt ON pt.id = ri.pattern_id
JOIN problems p ON p.id = ri.problem_id
WHERE ri.roadmap_code = $1
ORDER BY ri.position ASC
`

type ListRoadmapItemsRow struct {
	Position     int32
	PatternCode  string
	PatternName  string
	ProblemID    int64
	ExternalID   pgtype.Text
	ExternalSlug string
	Title        string
	Url          string
	Difficulty   pgtype.Text
}

func (q *Queries) ListRoadmapItems(ctx context.Context, roadmapCode string) ([]ListRoadmapItemsRow, error) {
	rows, err := q.db.Query(ctx, listRoadmapItems, roadmapCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoadmapItemsRow
	for rows.Next() {
		var i ListRoadmapItemsRow
		if err := rows.Scan(
			&i.Position,
			&i.PatternCode,
			&i.PatternName,
			&i.ProblemID,
			&i.ExternalID,
			&i.ExternalSlug,
			&i.Title,
			&i.Url,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
