ALTER TABLE users
  ADD COLUMN IF NOT EXISTS notify_review_reminder BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS notify_weekly_digest   BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS notify_email_enabled   BOOLEAN NOT NULL DEFAULT TRUE;
